### ISSUE TITLE
NOT AN ISSUE : is this the official/live repo  ?

### ISSUE THREAD

**Issue by GLLM** [odebroqueville/contextSearch#1]
Hi dev !

I was monitoring this repo, and when Githubwas qquired by Microsoft, it seems it went off ... and re-poppped up at Gitlab.

Is this the one to use to report issues & do some feature request/proposal ?

Thanks a lot for this great extension I couldnt live without

GLLM

**Comment by odebroqueville** [comment]
@GLLM After MS acquired GitHub, I thought of moving everything to Gitlab. But there were existing links to issues in GitHub all over the place, namely in User Reviews, so I changed my mind and brought everything back to GitHub. But there was a catch: while there's no problem importing issues from GitHub to Gitlab, the opposite isn't true! So yes, this is where the official work on the extension will remain, but I still need to find a way to bring the list of issues back from Gitlab!

**Comment by GLLM** [comment]
I see !
Merci :)
