### ISSUE TITLE
Auto-save not working

### ISSUE THREAD

**Issue by JohnLukeBentley** [odebroqueville/contextSearch#10]
When trying to save preferences, namely by clearing all search engine selections and then selecting a few: all the search engines disappear from the context menu.

There is also no [Save Preferences] button visible in the options screen. That is, as depicted at https://addons.mozilla.org/en-US/firefox/addon/contextual-search/?src=featured#&gid=1&pid=3

On FF 65.0.2 (64 bit).

**Comment by odebroqueville** [comment]
The "Save Preferences" button is no longer necessary and has been removed because the settings should be auto-saved. A new update of the extension will soon be released. When it is, if you still experience some quirks, then please report them here. Thanks for bringing this to my attention.

**Comment by odebroqueville** [comment]
@JohnLukeBentley Release 3.8.0 should fix any auto-save issues you may have experienced in the past. Please let me know if I may now close this issue. Thanks.
