### ISSUE TITLE
Import search engines from mycroftproject.com is impossible

### ISSUE THREAD

**Issue by Vingolf** [odebroqueville/contextSearch#103]
**README.md**

[How to add a search engine to your custom list](https://github.com/odebroqueville/contextSearch#how-to-add-a-search-engine-to-your-custom-list)
-  visit mycroftproject.com and right-click on the main link of a listed search engine

**Issues**
1. currently mycroftproject.com does not allow right-click 
2. even when right-click is enabled, adding a search engine is not possible
3. It is still possible, to [install](https://mycroftproject.com/install.html) a search engine to Firefox

**To Reproduce**
1. Go to [Mycroftproject.com_Top 100](https://mycroftproject.com/dlstats.html)
2. Right-click on the main link of a listed search engine
3. There is no possibility to add a search engine to Context Search
4. Try to add a search engine to Firefox. This is expected to work

**Expected behavior**
1. Right click is possible
2. The context menu offers a possibility to import the seach engine in Context Search.

**Desktop:**
- Windows 7 - 32 bit
- Firefix 83.0

#60 could offer a workaround to import search engines to Context Search

**Comment by odebroqueville** [comment]
You're right, something's broken! Will look into it when I have some time. Thank you for reporting this bug.

**Comment by odebroqueville** [comment]
Fixed in release 4.2.1. Please check and let me know if it now works for you.

**Comment by Vingolf** [comment]
I have checked context search on mycroftproject with release 4.2.5 on 

Desktop:

    Windows 7 - 32 bit
    Firefix 83.0

It is working now. Congratulations!
