### ISSUE TITLE
FF ERR (browser console): sendRemoveListener on closed conduit olivier.debroqueville@gmail.com

### ISSUE THREAD

**Issue by Hochiss** [odebroqueville/contextSearch#104]
Many thanks for this extension, I use it as dictionary lookup at macOS FF. But recently I notice above ERR:

![FF_ERR](https://user-images.githubusercontent.com/36304198/107507359-bb395180-6b9f-11eb-98f2-8186d3160347.png)

What's that? would you please review this?

**Comment by odebroqueville** [comment]
You needn't worry about it! That's what I was told by Mozilla Support!
