### ISSUE TITLE
Icons do not show

### ISSUE THREAD

**Issue by Hypernut** [odebroqueville/contextSearch#107]
The search engine icons do not show in the context menue anymore. The related option in the settings menu is buggy as well, the checkbox does not change its state if clicked on.

Otherwise great extension!
Thanks, Hypernut

**Comment by odebroqueville** [comment]
Sorry for the late response but I can't reproduce your issue. We would need more information about your environment and the versions you're running. Please try re-installing the extension and make sure that you are using the latest version 4.1.6.
