### ISSUE TITLE
Update URI for Wikipedia in defaultSearchEngines.json

### ISSUE THREAD

**Issue by AdrianAvenarius** [odebroqueville/contextSearch#108]
In defaultSearchEngines.json, line 223,
"url": "https://en.wikipedia.org/wiki/wiki.html?search="
should be
"url": "https://en.wikipedia.org/w/index.php?search=",
methinks.

**Comment by odebroqueville** [comment]
You're absolutely right! Will update the search engine in the next release (4.2.1). Thank you.
