### ISSUE TITLE
Remove Page action icon from url address bar

### ISSUE THREAD

**Issue by vayulove** [odebroqueville/contextSearch#109]
The location bar has an "Add Search Engine to Context Search" icon in it.  I want to remove that icon from the location bar, the latest Firefox only gives me the option to remove the whole addon.  How do I clean up my location bar to remove Context menu icon from it?

**Comment by e-pirate** [comment]
Same here. Please, add the ability to remove "Add Search Engine to Context Search"  icon from the address/location bar.

**Comment by odebroqueville** [comment]
The next release (4.2.1) will only display the Page action icon if there is an open search plugin available on the website being visited. However, if you've already added the search engine, the icon will still be displayed. I may improve this behaviour at a later stage. For the mean time, this is the best I can do without completely removing the feature that others may find useful.

**Comment by vayulove** [comment]
Thanks in general for this plugin. It is one of my most used plugins and 
I just love it.

**Comment by odebroqueville** [comment]
You're very welcome. I'm happy that you like it. Best wishes for the holidays.
