### ISSUE TITLE
Can't select text in the sidebar search results

### ISSUE THREAD

**Issue by kalpaucjusz** [odebroqueville/contextSearch#110]
As above. No mater what search engine I use, I can't select text when the results open in the sidebar. Is this intended behavior? Firefox API limitation?

**Comment by odebroqueville** [comment]
To my knowledge, this is a Firefox API limitation. I would have liked to implement that feature so that search results appear in the main window. I'm keeping this on my radar, but I think it still isn't possible. If I'm not mistaken, I think this kind of feature is available in Vivaldi.

**Comment by odebroqueville** [comment]
A [fix](https://discourse.mozilla.org/t/cant-select-text-displayed-in-the-sidebar/90833) will be provided in the next release 4.2.4.

**Comment by kalpaucjusz** [comment]
Thanks. And Happy New Year!

**Comment by odebroqueville** [comment]
Happy New Year.
