### ISSUE TITLE
[Feature Request] A keyboard shortcut for search engine

### ISSUE THREAD

**Issue by didli** [odebroqueville/contextSearch#113]
Hi !
I could get a little boost in productivity if I could get a way to : select a word, then run a search in a background tab through contextSearch with a keyboard shortcut (which would be assigned to a specific search engine)
But would that be possible to implement please ?
Thank you for your infos

**Comment by odebroqueville** [comment]
I think it's feasible, but you'd need a pretty good memory if you have many search engines! Have you tried the omnibox search?

**Comment by didli** [comment]
This keyboard shortcut in Context Search would be only useful to me for one specific search engine (that's my use case). The menu is fine for me for every others search engine. I don't use the omnibox search which is even more unconvenient for this particular use case. At work, I use one search engine in particular quite often (like, VERY often) and having to browse the menu everytime is slowing me quite a bit. So I'm searching for a way to shorten the time with the selection to run the associated search engine. Maybe it's way too specific, so we shouldn't bother at all ^^'
Still, thank you for your answer ! This is much appreciated.

**Comment by odebroqueville** [comment]
The feature has been released in v4.2.3. Note that not all key combinations will work as some may be reserved by Firefox or your system. Please give it a try and let me know how it goes.

**Comment by didli** [comment]
It works amazingly well ^^ ! Quite a boost in my productivity as well, thank you !
