### ISSUE TITLE
Twitch.tv volume control does not work 

### ISSUE THREAD

**Issue by GonGmata** [odebroqueville/contextSearch#116]
[https://www.twitch.tv](url) 

Volume control does not work, it always jumps back to the previous setting.

Tested with new Firefox(95.0.1 Linux) Profile only ContextSearch(4.2.1) extension
with ContextSearch(4.2.0) no problem

**Comment by Bentic77** [comment]
Other websites too with sliders. Always jumps back.

**Comment by odebroqueville** [comment]
Should be fixed in the latest release v4.2.2. Please let me know.

**Comment by Bentic77** [comment]
> Should be fixed in the latest release v4.2.2. Please let me know.

Yes is working again. Thanks for you great work.

Little sidenote, would love an option for putting the context menu option at another position if I rightclick a marked word.
