### ISSUE TITLE
Latest update today removed the 1st search entry from list and all favicons are gone.

### ISSUE THREAD

**Issue by jkuj6** [odebroqueville/contextSearch#117]
I don't know what you did, everything was working perfectly until the latest update today 25 December f**@!ed up the first search entry disappeared and as well as all favicons are gone.

**Comment by jkuj6** [comment]
I also tried to reset the favicons only, but when i did that, it re-arranged my whole list so i resotred my list from backup and still no favicons and 1st search entry doesnt appear as i said.

**Comment by odebroqueville** [comment]
Sorry to hear about your trouble with the extension update. Please try uninstalling the extension and then re-installing it and importing your search engines.

**Comment by jkuj6** [comment]
That only helped with getting my icons back but the first search entry is still missing.  There was nothing wrong with my extension. it broke while i was using firefox because of the auto-update that allowed for this extension.
I already tried a fresh clean Firefox with an installation of Context Search, you will see even with the default search entries that the first one "amazon" is missing from the right click menu.

Test it on a fresh friefox yourself to see.

**Comment by odebroqueville** [comment]
Sorry about that and thank you for reporting this issue. A fix has just been released in v4.2.3. Please let me know how it goes.

**Comment by jkuj6** [comment]
Its back now, thanks
