### ISSUE TITLE
Open search tab next to current tab

### ISSUE THREAD

**Issue by nth10sd** [odebroqueville/contextSearch#12]
Currently, when we have a lot of tabs, and we use Context Search in a tab that is locate in the middle (i.e. not the right-most), the new tab is opened all the way to the right side.

Would it be possible to open the new tab right next to the current tab? Should these [lines of code](https://github.com/odebroqueville/contextSearch/blob/master/background.js#L121) be altered?

**Comment by odebroqueville** [comment]
Good idea! We'll probably have to use tabs.getCurrent() and tabs.move(). I don't think we can use this in background.js or selection.js. Found some documentation here: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs

**Comment by odebroqueville** [comment]
This feature has been implemented in version 3.17 which has just been submitted for review to Mozilla, so it should be released by tomorrow.

**Comment by vuaru** [comment]
Not to be a downer, but I personally would like them to always be opened all the way to the right.
Perhaps it would be better to use ```about:config```'s ```browser.tabs.insertRelatedAfterCurrent```?
Or, if that's not possible with the WebExtensions API, make it an option.

**Comment by Smile4ever** [comment]
@vuaru What are you asking here? Are you asking for the equivalent of browser.tabs.insertRelatedAfterCurrent set to false?

**Comment by vuaru** [comment]
@Smile4ever Yes, which is how it worked before.
