### ISSUE TITLE
Recherche Larousse

### ISSUE THREAD

**Issue by Marie-Antoinette** [odebroqueville/contextSearch#12]
Bonjour,

Merci pour votre plugin.
Je rencontre un problème avec les recherches sur le site Larousse; pour une raison que je n'arrive pas à déterminer la recherche n’aboutit pas dans certains cas (indépendamment du site source).
mon setting:
https://www.larousse.fr/dictionnaires/francais/%s/?q=%s

Il semble y avoir un problème avec les accents également.

Merci

**Comment by odebroqueville** [comment]
Bonjour M-A, j'ai remarqué que le Larousse introduisait des chiffres (aléatoires?) dans les liens lors des recherches (peut-être pour décourager l'utilisation de leurs dicos via des requêtes HTTP). Ceci dit, j'ai qd même réussi à l'utiliser avec la chaîne de requête suivante:
https://www.larousse.fr/dictionnaires/francais/%s
Essayez et dites-moi si ça fonctionne. A part cela, des bugs sont survenus depuis les dernières mises à jour de Firefox. Une mise à jour de l'extension sera bientôt disponible pour corriger les problèmes.
Pour les accents, avez-vous des exemples?

**Comment by Marie-Antoinette** [comment]
Merci pour votre réponse, mais le problème reste le même parfois ça marche mais pas à tout les coups. 
Concernant les accents ( je pense que c’est du coté du site Larousse), prenez un mot avec é ou è par exemple et lancez une requête sur le site Larousse, si la requête aboutit le caractère accentué est remplacé dans l'invite Larousse et donc une liste de mots possibles est affichée. 
Le succès de la requête est aléatoire… 

Pour info: j'ai Larousse dans mes moteurs de recherche (Firefox 66.00); et lorsque je passe par l'invite de Firefox de recherche, les requêtes aboutissent toujours mais sur les mots contenant des lettres accentuées le mot est mal affiché dans l'invite Larousse mais la définition est bien affichée (peut-être une indication pour vous). 
Ceci dit le plugin fonctionne et pour Larousse je fait un copier/coller. 

----- Mail original -----

De: "Olivier de Broqueville" <notifications@github.com> 
À: "odebroqueville/contextSearch" <contextSearch@noreply.github.com> 
Cc: "Guillaume" <terex@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 25 Mars 2019 16:59:06 
Objet: Re: [odebroqueville/contextSearch] Recherche Larousse (#12) 



Bonjour M-A, j'ai remarqué que le Larousse introduisait des chiffres (aléatoires?) dans les liens lors des recherches (peut-être pour décourager l'utilisation de leurs dicos via des requêtes HTTP). Ceci dit, j'ai qd même réussi à l'utiliser avec la chaîne de requête suivante: 
https://www.larousse.fr/dictionnaires/francais/%s 
Essayez et dites-moi si ça fonctionne. A part cela, des bugs sont survenus depuis les dernières mises à jour de Firefox. Une mise à jour de l'extension sera bientôt disponible pour corriger les problèmes. 
Pour les accents, avez-vous des exemples?
