### ISSUE TITLE
Edit existing search engines

### ISSUE THREAD

**Issue by brnl** [odebroqueville/contextSearch#123]
It would be awesome to be able to edit existing search engines.

Alternatively, it could also help if you populate the 'Add a new search engine' fields with the last deleted search engine, so you can change what you want and add it again. Then you only have to move it to it's old position again.

**Comment by odebroqueville** [comment]
"It would be awesome to be able to edit existing search engines." ---> I don't see what you mean! It is possible to edit existing search engines!
"it could also help if you populate the 'Add a new search engine' fields with the last deleted search engine" ---> This will not be implemented for 2 reasons: if a user doesn't want to see a search engine in the context menu, then he or she may uncheck it. It is not necessary to delete a search engine if a user isn't certain if he or she may need it later. The second reason is that I don't get a lot of help from my co-developer, who is more proficient than I am when he doesn't cause memory leaks(!), and end up doing most of the work. There's a ton of work that has higher priority, for which I get nothing in return btw.

**Comment by brnl** [comment]
Oh dear, I haven't saved my edit that I wanted to do, sorry. I was wrong about it not being editable. The only thing that you can't change is the name, so therefore the request may remain.

But feel free to put this one way down to the end on the priorities list.
