### ISSUE TITLE
Default search engines, opening in tabs and  adding sites from search box.

### ISSUE THREAD

**Issue by harryray33** [odebroqueville/contextSearch#126]
1. I've just installed this...I I would like to have this show the search engines I already have installed but instead it's just showing the default search engine list.
Is there a way to have my engines showing instead of the default? I've tried import but that didn't work.

2. Although I have set options to open in tabs, when I search multiple engines it opens in a new window instead of tabs.

3. Is there a way of right clicking a search box on a site and including the site on the list?

Thanks

**Comment by odebroqueville** [comment]
1. If you're referring to search engines in Firefox, unfortunately Mozilla doesn't provide an API to export its search engines.
2. Multi-search opens a new window to avoid cluttering the active window.
3. I think another similar extension has implemented this feature, but I have no idea how it's done!

**Comment by harryray33** [comment]
OK, thanks. is there a way I can get around opening in a tab instead of a window?

Yes, I've found a couple of other add-ons which automatically populate the engine list with the existing engines (ones that are the default and ones that I have added, but I like the multi search facility on yours.

**Comment by odebroqueville** [comment]
Hi Harry, If I understand you correctly, you'd like multi-search to open in tabs on the active window. This has to be implemented with a new option and it's not on my priority list right now, so you'll have to be patient.

To my knowledge, importing search engines can be done using a hack, but I find that disgraceful and won't implement it until Mozilla provides us with a convenient API.

The import/export features are only useful with this extension and are intended to serve as a backup if anything goes wrong with the extension, namely after browser updates that could break things.
