### ISSUE TITLE
Please remove all console.log calls from the released version

### ISSUE THREAD

**Issue by Sarkos** [odebroqueville/contextSearch#127]
I can't use my console with this addon installed, it is entirely full of keydown events.

**Comment by odebroqueville** [comment]
Sorry about that @Sarkos . Will remove them in the next release. Btw, are you greek?

**Comment by Sarkos** [comment]
Thanks! No, I just read somewhere that "sarkos" was the root of the word "sarcasm" and thought it would make a good nick :)
