### ISSUE TITLE
[Documentation] advanced features 

### ISSUE THREAD

**Issue by Vingolf** [odebroqueville/contextSearch#129]
Hi @odebroqueville

1. is there a documentation of the **advanced features**
 to use regular expressions to build the context menu❓
2. I can't find the **icon grid**, although this feature is not disabled 🤷‍♂️
 (Win7 FF83 and Win10 FF93)

**Comment by odebroqueville** [comment]
1. Sorry, there is no documentation for the advanced features, but it’s really quite straight forward: you just add a regular expression to each search engine. If the selected text matches the regex, then the search engine will appear in the context menu.
2. The grid of icons should appear when you press the Alt key on your Windows keyboard and left click on your mouse. It works on Mac but I’ve never tested on Windows!

**Comment by Vingolf** [comment]
> 2. The grid of icons should appear when you press the 
Alt key on your Windows keyboard and left click on your mouse.

Ohh yes, it works as you describe it [Alt-click on selected text], 
both on (Win7 FF83 and Win10 FF93) :blush: 

> 1. [advanced features] - it’s really quite straight forward: [...]
 If the selected text matches the regex, 
 then the search engine will appear in the context menu.

Can you describe it or give an example for it?
        I wonder if there is a context, where this  could be useful for me 🤔

Btw, I made a  comment on [ bdbbe80](https://github.com/odebroqueville/contextSearch/commit/bdbbe800af296ed21b7e5d6dcd033a90e7e9a875#commitcomment-62938045).
 I'm not sure if this was the right place to do so 🙄

**Comment by odebroqueville** [comment]
As an example for the advanced feature, imagine you had a search engine for booking.com and another for tripadvisor.com and you would like these search engines to appear in the context menu when a selection contains the word hotel. Then, for those search engines, you'd enter the regex /hotel/. If you then make any other selection that doesn't contain the word "hotel" in it, those search engines won't appear in the context menu. There's a very useful website for building your regex: [https://regex101.com](https://regex101.com)

Thank you for your comment, even though it's not in the right place. You can just send me an email in the future. Your comment is absolutely valid and I'll make the changes in the next release.
