### ISSUE TITLE
Available favicon missing when adding a new search engine

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#130]
Your are doing a great job with this extension. &#128077;

I support this proposal and I have already an issue with a favicon. 

My problem is not visible in the base64 code in the searchEngines.json 
so I describe some steps to reproduce.

**Issue**
Context Search uses none respectively a wrong favicon for www.ebay-kleinanzeigen.de

**To Reproduce**
1. Add www.ebay-kleinanzeigen.de as a search engine to Context Search.
2. Context Search shows in the sub-context menu a placeholder favicon like this
https://api.faviconkit.com/www.ebaykleinanzeigen.de/64
3. The correct icon is this one
https://api.faviconkit.com/www.ebay-kleinanzeigen.de/64

**Feature Request**
1. The possibility to change or to edit the favicon url. 
2. This picture  gives an impression of such a feature.
https://abload.de/img/add-on-swift-selectio8pj02.jpg

Edit (06.01.22):
Since the [favicon.com](https://faviconkit.com/#comment-5508814804) service is down,
 I provide another link to the [ebay-kleinanzeigen.de favicon](https://www.ebay-kleinanzeigen.de/static/img/favicon.png)

_Originally posted by @Vingolf in https://github.com/odebroqueville/contextSearch/issues/64#issuecomment-796306496_

**Comment by odebroqueville** [comment]
@Vingolf Thank you for reporting this issue. It made me discover a few bugs and do some code cleanup! Version 4.2.6 has just been released with a fix for the above. I suggest you delete the search engine that you added for http://www.ebay-kleinanzeigen.de/ and then navigate to that page in Firefox. You will notice the Context Search icon in the url address bar. Simply click on it to add your search engine. The correct favicon should have been added.

**Comment by Vingolf** [comment]
> @Vingolf Thank you for reporting this issue.  
> delete the search engine that you added for http://www.ebay-kleinanzeigen.de/ and then navigate to that page in Firefox. 
> You will notice the Context Search icon in the url address bar. Simply click on it to add your search engine. 
> The correct favicon should have been added.

@odebroqueville, yes, it is working now as you describe it. The favicon for ebay-kleinanzeigen.de appears in the context menu.
Good job! 👍
