### ISSUE TITLE
Add a new search engine from an input search box

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#132]
This feature is required to support websites that use form submissions or HTTP POST requests to search their website.

**Comment by xbbdc** [comment]
Hello. I'm not sure if I should open a new issue, but I am now experiencing this problem. For example, when I go to Google Maps page and do a search, and then double click a word in the search box, your addon now opens a window to try and add new engine.

I dont know if its a bug or how to turn it off, but i want it off.
![1](https://github.com/odebroqueville/contextSearch/assets/59808960/b693ff00-e269-44d3-9ed1-c6933c4cb561)

**Comment by odebroqueville** [comment]
@xbbdc  This should be fixed with version 4.7.1. Let me know if you're still having issues.

**Comment by xbbdc** [comment]
@odebroqueville it is fixed! thank you!
