### ISSUE TITLE
JS error in browser console (each tab)

### ISSUE THREAD

**Issue by OlliZabal** [odebroqueville/contextSearch#137]
FYI: I'm receiving a JS error latley  at the browser console (each tab) using your latest plugin version, latest Firefox on a Win 10 PC.

Error:
`IndexSizeError: Selection.getRangeAt: 0 is out of range selection.js:342
    getSelectedText moz-extension://adf201ea-8e55-4a78-ac25-5893282f5422/scripts/selection.js:342
    handleKeyUp moz-extension://adf201ea-8e55-4a78-ac25-5893282f5422/scripts/selection.js:161
`

Besides, also all search engine icons are no more showing up on the context window.

Edit: export function does also not work anymore... strange.

**Comment by odebroqueville** [comment]
Hey Olli, I'm not certain, but it looks to me that your install of Context Search might be corrupt. I would recommend uninstalling it after you've exported and saved your search engines. Then you can re-install Context Search and import them. Please let me know if you still encounter errors after that. Sorry for the trouble!

**Comment by OlliZabal** [comment]
Hi Olli ;), I tried several times removing and fresh re-installing your extension. The first mentioned JS erros still occurs unfrequently as before.

**Comment by odebroqueville** [comment]
Hey Olli, has this been fixed for you or are you still seeing some errors? Can I close this issue?
