### ISSUE TITLE
Favicons missing

### ISSUE THREAD

**Issue by airone506** [odebroqueville/contextSearch#138]
Hello, first of all I would like to **thank you for this extension**. There are some similar, but this one is the one to go for me. I like the configuration options and I also appreciate it for being open source.

Now about the issues.
1) All the favicons are missing. I tried to reset it using settings UI (`Force favicons to be reloaded`) and it actually made them disappear. With some tinkering and resetting everything in `Reset options` pane I am actually able to get the favicons back, but only sometimes, and only some of them, the rest have the default icon (the same as the extension itself uses, the globe with magnifier). I can never get the corresponding icons for the newly added search engines. What is the expected behaviour of `Force favicons to be reloaded` actually?

2) The `Display favicons in context menu list` in the `Favicons & Icons` can not be unchecked.

3) The `Export search engines to JSON` in the `Import/export search engines` does not work in the LibreWolf browser, it is a fork of Firefox built without telemetry and it provides enhanced privacy and security. The export works in the recent Firefox though.

My version of Context Search is 4.4.3 from March 29, 2023, there isn't the newer version available at the AMO website yet.

I would be happy to provide any additional information if needed.

**Comment by odebroqueville** [comment]
What is your OS? I'm under the impression that your install is corrupt. First, I would strongly recommend to export/download you list of search engines. Have you enabled the permission for downloads? When you force favicons to be reloaded, CS will visit the domain of each search engine and look for its favicon. After you've saved your search engines, I would uninstall CS and then re-install. Finally, import your list of SE and check if it's working. I wouldn't mess too much with the reset options. It does many async requests and it seems to bring some instability to the extension.

**Comment by airone506** [comment]
Thanks for the reply. 

The OS is Linux. I've enabled any permission I've been asked for by the extension. I did some additional checks and I found out that `Reset preferences to default settings` actually brings the favicons back. `Force favicons to be reloaded` has no effect for me. I'm getting the proper favicons only for engines like DuckDuckGo and Wikipedia, I'm getting the generic favicons (the globe with magnifier) for the engines like Wiktionary, Invidious (both added by clicking on icon in URL bar) and DeepL (added manually by pasting search URL in config page of the CS). 

> 2) The `Display favicons in context menu list` in the `Favicons & Icons` can not be unchecked.

On a second thought, this can be actually the reason for the disappearing of the favicons. It can't be unchecked, but it can be clicked and makes favicons disappear. It can not be reverted because it is still checked, it can not be checked again, but the `Reset preferences to default settings` actually reverts it.

Summary:
- The `Display favicons in context menu list` in the `Favicons & Icons` can not be unchecked and quirky behaviour can be observed.
- I can not get the proper favicons for some search engines.

**Comment by odebroqueville** [comment]
Thank you for the detailed feedback. Definitely helps. I don't have Linux, but I'll do some testing on mac to see if I get the same results. This might take a bit of time to debug so please bare with me.

**Comment by airone506** [comment]
In the meantime I downloaded the missing favicons manually from the related websites, base64 encoded them and edited the `.json` config file manually as a temporary solution. This extension is so good that it was well worth the effort. 👍 🙂

**Comment by airone506** [comment]
Just for the record, everything seem to be working well in the newly released version. Thank you for the fixes.
