### ISSUE TITLE
Unable to save settings to local disk

### ISSUE THREAD

**Issue by BrankoDijkstra** [odebroqueville/contextSearch#139]
For quite a while I have been unable to save settings to local disk. Pressing the button (seemingly) seems to do nothing.
Firefox 112.0.2 (64-bit) Windows 11

**Comment by odebroqueville** [comment]
You need to enable the Downloads permission in the extension’s settings. When you encounter an issue please read the extension’s description or check that your issue has already been encountered by others in reviews or closed issues. I’m often having to repear myself.Thank you and regards,Olivier On 1 May 2023, at 00:51, BrankoDijkstra ***@***.***> wrote:﻿
For quite a while I have been unable to save settings to local disk. Pressing the button (seemingly) seems to do nothing.
Firefox 112.0.2 (64-bit) Windows 11

**Comment by BrankoDijkstra** [comment]
apologies, I did search in a few location and did not find this detail. Now you mention it I can find this well hidden in between some other issues.

thanks for your reply; I'll try to do better next time.
