### ISSUE TITLE
Automatic update to 3.70 resets search engine list

### ISSUE THREAD

**Issue by MirekGH** [odebroqueville/contextSearch#14]
After auto-update of addon to 3.70 version in Firefox (v. 66 and v.67beta) I lost all my search engines that were manually added (there was a popup saying that default list was loaded).
Same happened after each restart of the browser.
I noticed that in addon options now there is (checked by default) option to: "Force reload of default search engines list".
Unchecking it solved the problem - but had to use backup of my profile (twice) to restore lost search engines.

**Comment by zippit** [comment]
Adding to the above... after unchecking and restarting the browser, if Force reload is unchecked not context search is available with right click.

**Comment by MirekGH** [comment]
I didn't notice it at first, but I confirm what @zippit wrote. As a temporary solution you can toggle it (or some other option) on and off after each restart of the browser (in order to restore context menu).

**Comment by odebroqueville** [comment]
I'm very sorry for the trouble caused. I reverted things back to the former version, but I believe the latest firefox updates have broken the up and down arrows. That's why I was in a hurry to provide an update. Please always create a BACKUP of your custom search engines list by using the export button on the extension's preferences page. It will keep you safe for times when trouble comes. I'm no javascript expert so this will inevitably happen from time to time. In the mean time, I will seek help to debug and test the extension more thoroughly.

**Comment by DRSAgile** [comment]
Indeed, this is an issue.

I might be wrong as I only looked at the code superficially, but the problematic part might be a part of the initialization code that is either fails to get non-empty data from the local storage or mistakenly decides that the promised value it has gotten is empty and hence loads default options which, by an unfortunate coincidence, include the forced reset option, what leads to all of the custom search engines wiped out.

**Comment by odebroqueville** [comment]
Is this issue resolved with 3.72?

**Comment by DRSAgile** [comment]
Thanks for the prompt. I have updated the extension to 3.72 version now. I will check what will happen after the browser will be restarted, but for now, the search engines list is still intact, which is a good sign.

But the browser console's (Control+Shift+J) error "SyntaxError: redeclaration of const logToConsole @search_results.js:1:1" is sill there.


Olivier, can check the code? You might put the _const_ declaration inside a condition that checks if it already exists in the environment or not, and then the error will go away:

```
  if (typeof logToConsole === 'undefined')
  {
    const logToConsole = 'something';
  }  
```

Or you can wrap the whole script in IIFE (Immediately Invoked Function Expression) so your constant would not be kept in the browser environment in between the script's calls:
```
(function()
{
    // some code
}
)()

```

**Comment by odebroqueville** [comment]
@DRSAgile Thanks for the good suggestion. I'll make the changes for the next release.

**Comment by zippit** [comment]
Yes, that seems to be the case. Appreciate your work on this great extension.

**Comment by odebroqueville** [comment]
@zippit Thanks. I'll close the issue for now.
