### ISSUE TITLE
Add option to make the grid of icons appear when text has been selected

### ISSUE THREAD

**Issue by angelfire76** [odebroqueville/contextSearch#143]
Hey there,
The icon grid only appears when I pressed ALT+LEFT CLICK but it's immediately disappear when I take the cursor out of the grid. Also the grid items doesn't change when I selected the sites. It only shows the default sites.
Can you add another feature such as the icon grid appears when a text has selected (no need for another key or click to trigger) and only disappear when the site has selected?
It'd also be good to disable it via the options.
Also it would be great to have a shortcut (like only "m" or custom selection textbox so we can choose) for multi-search when a text has selected.
Thanks in advance.

**Comment by odebroqueville** [comment]
Implemented since v4.5.5.
