### ISSUE TITLE
Icons Grid does not close in some cases

### ISSUE THREAD

**Issue by tkapias** [odebroqueville/contextSearch#154]
Thank you for this addon, I removed 3 other addons thanks to it.

## Issue

I use the Icon Grid options implented in [4.5.5](https://github.com/odebroqueville/contextSearch/commit/54d267006f0550b27f278d5317ee1d170b74abf9) to **open/close at selection/mouse-off**.

But in some situations the grid stays in place and does not disappear even on a new selection.

### Details

In some places, like a Gitlab project page or in the writing field on Github:
  - Every kind of text selection in the same element (div, frame...) makes the grid stuck in place (sliding mouse selections or double/triple clicks on words/sentences).
  - The grid disappears only with a click on itself or with a selection in on test in a different element, or if you make a different kind of selection (from click to sliding selection). 

In plain pages, like blogs, it's more complex.
The grid stays stuck only if you select by multiple clicks and then deselect by a click on the same word :
  - Select a whole word by a double click and keep you mouse one the selection.
    - The icon grid appear.
  - Click one time in the word again to deselect.
  - Move you mouse away.
    - The grid does not close or move.
  - Double click on another word.
    - The old grid is still at the old place.

- In all cases the URLs in the icons are still updated to the new selection in the grid that was stuck.

### Other

I use another addon that displays floating elements on selections. It's not maintained, but simple and works well enough, maybe you could compare, there is a github: 
- [wikipedia-anywhere](https://addons.mozilla.org/fr/firefox/addon/wikipedia-anywhere/)

### System

- Firefox: 103.0.2 
  - with `clipboard.autocopy: false`
  - Linux: Debian Testing

**Comment by tkapias** [comment]
I forgot to say that in all cases, if you move your mouse on the grid and then off, it will always disappear.

So the issue is probably with the fact that tehe early design of the code is intended for the user to move it's mouse on/off the grid every time.

A solution would be to open the grid under the mouse, but most of the time I select text to copy it with a keyboard shortcut and I want to see it. **I think that the grid already opens too close to the selection, it sould be a few pixels under/over it**.

Then there is the solution of the keyboard shortcut like suggested in your issue #147.

But I would prefer something like [wikipedia-anywhere](https://addons.mozilla.org/fr/firefox/addon/wikipedia-anywhere/).

**Comment by odebroqueville** [comment]
@tkapias Hi Tomasz, thank you for this clear issues report. Is there a reason that you're not using the latest version of Context Search (4.6.2)? If I remember well, I think v4.6.2 fixes the sticky Icons Grid problem. I'm not certain though! Would you please check and let me know? Concerning the positioning of the Grid, I honestly haven't given it much thought. I'll try to find some time to take a closer look into how the positioning may be improved.

**Comment by tkapias** [comment]
I checked and I am currently using v4.6.2, I think that it was the same earlier because the issue is still here.

But in the mean time, I discovered that I can disable the grid and make it appear only if I press the ALT key when I select. It's still a little buggy because I have to deselect 2 times before each use, but it's only on demand (when I press ALT) so much more bearable.

I will record some gifs.

**Comment by tkapias** [comment]
How I use it actually:

Pressing ALT when I do a mouse selection. But I can not do it 2 times in a row, and I have to click on the grid to make it disappear.

https://github.com/odebroqueville/contextSearch/assets/45816387/4a758424-14dc-45e6-830b-8a194300bb34

**Comment by tkapias** [comment]
How I used it before with auto open/hide:

It's v4.6.2 and issues like described at the top.

https://github.com/odebroqueville/contextSearch/assets/45816387/a8a3790d-5e73-4445-8ab5-13a468c9f1b5

**Comment by odebroqueville** [comment]
@tkapias Hi Tomasz, do you know how to test an extension from the 'about:debugging' url? I think that I've fixed the bug you're encountering and would like you to test things on your end. I've uploaded the modified code to GitHub, so you can download the Zip file to test. Please let me know if you need more help to test.

**Comment by odebroqueville** [comment]
@tkapias Please give version 4.6.3 a try and let me know if it solves your issue.

**Comment by tkapias** [comment]
🎉 Firefox updated to 4.6.3 by itself and I just tried a moment ago, the problems listed above are **all solved**, Thanks. 


PS: maybe that it's a unique coincidence, but the first [bookmark](https://lescahiersdudebutant.arpinux.org/bookworm-fr/index.html) that I opened to test the addon has another issue with the grid, it's too large, even more than the wiewport sometimes. Do I open an issue about it? 

![image](https://github.com/odebroqueville/contextSearch/assets/45816387/7a9e137a-be3f-48cb-bc74-d93584d0f3b3)

**Comment by odebroqueville** [comment]
Hi Tomasz,Would you mind opening a new issue with the steps to reproduce the bug. This really looks problematic and needs to be addressed.Thank you in advance for your help.Good evening,Olivier On 16 Sep 2023, at 21:51, Tomasz Kapias ***@***.***> wrote:﻿
🎉 Firefox updated to 4.6.3 by itself and I just tried a moment ago, the problems listed above are all solved, Thanks.
PS: maybe that it's a unique coincidence, but the first bookmark that I opened to test the addon has another issue with the grid, it's too large, even more than the wiewport sometimes. Do I open an issue about it?

**Comment by tkapias** [comment]
Done in issue [154](https://github.com/odebroqueville/contextSearch/issues/155).
