### ISSUE TITLE
Disable extension debugging messages

### ISSUE THREAD

**Issue by Septh** [odebroqueville/contextSearch#156]
Hi, the extension is generating a lot of noise in the browser console, which is a real burden when trying to debug my own code. Could you please disable this in the production build? 🙏 

![image](https://github.com/odebroqueville/contextSearch/assets/11949623/01a9a91c-f2cf-47fa-87db-58d24ac503b6)

**Comment by odebroqueville** [comment]
Sorry about that! I have 3 files using a console logging variable and one slipped through the cracks! Whenever I code, I set all 3 debugging variables to true and when I'm finished I have to set all 3 variables back to false for publication. It's a bit of a nuisance really and I'm wondering if there's not a way to automate this process?

**Comment by Septh** [comment]
I am not familiar with browser extension development but I think [runtime.onInstalled](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled) can help, something like:

```js
let logToConsole = false
browser.runtime.onInstalled.addListener(evt => {
    logToConsole = evt.temporary
});

function log(...args) {
    if (logToConsole) console.log(...args)
}
```

**Comment by odebroqueville** [comment]
@Septh Nice one! Thank you, Stephan!
