### ISSUE TITLE
Multisearch opens one tab untill I press CTRL-T

### ISSUE THREAD

**Issue by ymmv99** [odebroqueville/contextSearch#158]
The Multi Search used to work fine for me, but a year or so ago whenever I did a multi-search only the first search engine would show the search results. Only when I press the shortcut to create a new tabs (CTRL-T), the tabs with the other search engines would open. 

Since this workaround worked I never bothered to create a bug report, but since this issue hasn't been fixed (for me at least), it's about time I created a report.

I'm using the latest version of Firefox.

**Comment by odebroqueville** [comment]
Thank you for reporting this. Please let me know which OS you use (sounds like you're on Windows) and which versions of Firefox and Context Search. Also, what are you multi-search settings? If I understand correctly, when you carry out a multi-search, only the first search result will open in a new window. Then, if you press CTRL-T, the other search results appear each in their own tab. The first thing I'd like you to try (to rule out any interference with another extension) is to enable Context Search in Incognito mode (making sure no other extension is allowed in Incognito mode). Then, open an Incognito window and see if you get the same behaviour.

**Comment by ymmv99** [comment]
I’ve found out how to fix the problem.

 

These are my settings:

 



 

With these settings I’ve got the issue that only the first search results is visible until I press CTRL-T and the other tabs are loaded with results.

 

But when I turn on the option “Make the new tab or Windows active” all search results are shown immediately. (This is in normal Firefox mode, so there’s no interference from other plugins).

That additional setting fixes my problem. 

 

BTW I’ve tried testing in incognito mode, but when I use the multi search all results are opened outside of incognito mode.

 

I’m running Windows 11 H2303 (latest patches), Firefox 119.0.1 and Context Search 4.7.1

 

BTW Thank you for this plugin, I’ve been using it for years. Couldn’t live without it.

 

Saskia

**Comment by ymmv99** [comment]
Oh, I noticed one thing though.

 

When I do a multi context search using a few search engines I get an empty “New Tab” after the last search engine tab in the new browser windows. I don’t think that’s supposed to happen.

 

Saskia

**Comment by odebroqueville** [comment]
Hi Saskia, I had noticed this, but I thought it wasn't a big deal and didn't want to risk deleting the wrong tab. I'll see what I can do for the next release if this really itches you!

**Comment by odebroqueville** [comment]
I am closing this issue as I have not heard back from you.
