### ISSUE TITLE
Requesting Dark Theme

### ISSUE THREAD

**Issue by lamyergeier** [odebroqueville/contextSearch#165]
Requesting Dark Theme. Presently its hard to read as can be seen below

![image](https://github.com/odebroqueville/contextSearch/assets/42092626/cedb2e97-fcf0-450d-9c35-b0e956f91d8f)

**Comment by lamyergeier** [comment]
@odebroqueville  Could you please save the preference if the person chooses the toggle dark theme once? And mab ne button can read "Toggle Theme" so it could remember the last setting and toggle from dark to light when clicked again.

**Comment by odebroqueville** [comment]
@lamyergeier Can I close this issue now?
