### ISSUE TITLE
Icons Grid won't arrange according to order set in preferences

### ISSUE THREAD

**Issue by lamyergeier** [odebroqueville/contextSearch#166]
In the following we can see the order of search engine

![image](https://github.com/odebroqueville/contextSearch/assets/42092626/b86d6cd3-be86-4079-a491-dbd0b474c7fd)

While the preferences are as follows

![image](https://github.com/odebroqueville/contextSearch/assets/42092626/2b81d666-8141-4074-9f4f-bc322c03698c)

**Comment by odebroqueville** [comment]
I'm closing this issue as I haven't heard back from you since I posted a fix 5 days ago.

**Comment by lamyergeier** [comment]
@odebroqueville 

> I'm closing this issue as I haven't heard back from you since I posted a fix 5 days ago.

The issue is solved.
