### ISSUE TITLE
Request: Icon Grid Positions

### ISSUE THREAD

**Issue by hasantahsindagli** [odebroqueville/contextSearch#168]
First of all, thank you for the plugin. I would suggest you add just one feature. The position of the icon grid can sometimes cause problems. I use other plugins and the Icon Grid location may prevent me from using them. It would be nice if we could adjust the Icon Grid position to get rid of this situation.
Thank you again.

![Clipboard Snapshot](https://github.com/odebroqueville/contextSearch/assets/62343087/f94dffec-5bd8-4cd2-aabd-f99883c8e2ef)

Request 2: Additionally, "Copy" and "Open in New Tab" buttons can be added for the selected text or links.

**Comment by odebroqueville** [comment]
@hasantahsindagli 
Honestly Hasan, I don't think the issue lies with the positioning of the Icons Grid, but rather with the position of that t icon which is coming from some other extension I guess. So, I would suggest that you raise the issue with those who are responsible for the positioning of the t icon. Also, kindly note that the Icons Grid will position itself where your Alt-Click when you uncheck the option "Immediately display the icons grid after text has been selected".

**Comment by hasantahsindagli** [comment]
> @hasantahsindagli Honestly Hasan, I don't think the issue lies with the positioning of the Icons Grid, but rather with the position of that t icon which is coming from some other extension I guess. So, I would suggest that you raise the issue with those who are responsible for the positioning of the t icon. Also, kindly note that the Icons Grid will position itself where your Alt-Click when you uncheck the option "Immediately display the icons grid after text has been selected".


You are right in what you wrote. I guess I didn't explain the situation. I just wanted to make a request. I wish there was an option where we could adjust the position of the Icon Grid. So, not issue, it was only request.

I also made another feature suggestion. Being able to copy the selected text with Icon Grid (to the clipboard) + open the text in a new tab (if it is a link).

Thank you. Best regards.

PS: Unfortunately, the plugin with the "T" (tureng) symbol does not have a location setting. It is also an extension ported from the Chrome browser.

**Comment by odebroqueville** [comment]
@hasantahsindagli I have just updated the extension (v4.7.8) to include the option to add a horizontal and vertical offset. The default is 12px, you can change it between 0 and 200.

![CleanShot 2024-03-10 at 19 39 45@2x](https://github.com/odebroqueville/contextSearch/assets/4818315/ebcc38bf-6261-4740-bdb3-4efee5e8e687)

**Comment by hasantahsindagli** [comment]
> @hasantahsindagli I have just updated the extension (v4.7.8) to include the option to add a horizontal and vertical offset. The default is 12px, you can change it between 0 and 200.
> 
> ![CleanShot 2024-03-10 at 19 39 45@2x](https://private-user-images.githubusercontent.com/4818315/311537958-ebcc38bf-6261-4740-bdb3-4efee5e8e687.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMDU4MjAsIm5iZiI6MTcxMDEwNTUyMCwicGF0aCI6Ii80ODE4MzE1LzMxMTUzNzk1OC1lYmNjMzhiZi02MjYxLTQ3NDAtYmRiMy00ZWZlZTVlOGU2ODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTBUMjExODQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2FiOWRiNzcxMTk2NWEzNWM5OTU1ZDhlYzZhYjkzZGE5MzQ0OWU4MDg1NjZmZWNkNDQzNGM2YWM4N2U4NDBiOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.07TjpA1jCZlforC67nxrWwogrKEnchzpjgFTuPiBp_A)

Thank you for the update
