### ISSUE TITLE
Question: If we unselect "Immediately display the icons grid after text has been selected" in the settings, is there any keyboard shortcut to display the icon grid?

### ISSUE THREAD

**Issue by lamyergeier** [odebroqueville/contextSearch#169]
If we unselect "Immediately display the icons grid after text has been selected" in the settings, is there any keyboard shortcut to display the icon grid? Or how to display the pop up grid?

**Comment by odebroqueville** [comment]
@lamyergeier  Yes, hold the Alt or Option key and then click on the web page where you'd like the Icons Grid to appear. It's explained in the extension's description page under "How does it work".
