### ISSUE TITLE
Unselecting search engines from the Options page doesn't remove them from the Icons Grid

### ISSUE THREAD

**Issue by lamyergeier** [odebroqueville/contextSearch#170]
> Readme.md
>
> The checkbox at the start of a line determines whether the search engine should appear in the context menu.

May be add another checkbox to hide certain search engine from icon grid.

**Comment by odebroqueville** [comment]
@lamyergeier  Do you mean that you'd want a different set of search engines for the Icons Grid to the ones for the context menu?

**Comment by lamyergeier** [comment]
Not necessary  but currently unselecting  search engines in settings has no effect on the icon grid.

**Comment by odebroqueville** [comment]
@lamyergeier 
Nice catch! Thank you.

**Comment by odebroqueville** [comment]
@lamyergeier Please close the issue if it's been resolved for you.
