### ISSUE TITLE
Multiple right mouse click options options broken in 5.0

### ISSUE THREAD

**Issue by ymmv99** [odebroqueville/contextSearch#175]
The **Multiple Search Engies Search** option worked fine in 4.78 but is broken in 5.00.  Nothing happens when I try to use it. 

Three other right mouse click options options that don't work anymore are **Search for an exact String Match**, **Search this site with Google** and **Options**.

**Comment by odebroqueville** [comment]
Thank you for reporting these bugs. I will look into it and release a fix over the weekend.
