### ISSUE TITLE
Allow for custom search engines for image searches

### ISSUE THREAD

**Issue by dude892** [odebroqueville/contextSearch#178]
Already have the context menu for right clicking an image and having the Google Lens and Google image search, would like to be able to add image only customizable searches.

**Comment by odebroqueville** [comment]
What do you mean by "image only customizable searches"? Do you mean that you would like to have the option to enable/disable the image search offered by Context Search?

**Comment by dude892** [comment]
No, I mean how we can currently add or remove search engines from the context menu, just being able to do the same with the context menu when right clicking an image, like being able to remove Google Lens and add something like TinEye.

**Comment by odebroqueville** [comment]
Sorry for the late response. I now better understand your request. It's a good idea and I should have thought of it sooner. Whilst I can't promise when it'll be implemented, I do promise that I'll look into it. Thank you.

**Comment by odebroqueville** [comment]
@dude892 I haven't heard back from you and I would need some clarifications to see how I could implement this feature: how would you see this working for TinEye, for example? Which search query string would you use?

**Comment by odebroqueville** [comment]
I am closing this issue as I haven't heard back from you and don't see how to make it progress.
