### ISSUE TITLE
ctrl-c starts search on britannica.com

### ISSUE THREAD

**Issue by rgoubet** [odebroqueville/contextSearch#179]
On one of my laptops, but not all, clicking on ctrl-c opens a search on britannica.com for the selected text.

This behavior is a big privacy issue, as you don't want text copied to the keyboard to be sent out in the open as a search term on an external website.

How can this be disabled without disabling the extension entirely (which does work)?

**Comment by odebroqueville** [comment]
You can easily change a keyboard shortcut by selecting it and using whatever key combination you fancy. Alternatively, you can use the "Clear all keyboard shortcuts" button to remove all of them.
