### ISSUE TITLE
Clicking on the trash can icon wipes all search engines

### ISSUE THREAD

**Issue by ThornyJohn** [odebroqueville/contextSearch#18]
I'm sure this is related to other recent reports, but no one seems to have reported it explicitly, so...

Regardless of how many search engines are selected/checkmarked (none, some, or all of them), clicking on the trashcan icon of any one of them wipes them all from the list.

**Comment by odebroqueville** [comment]
If you refresh the Options page, are they still all gone? (or just the one you deleted)

**Comment by ThornyJohn** [comment]
If I refresh the page, they do come back and the deleted search engine does go away correctly, so I guess it's a refresh issue?

**Comment by odebroqueville** [comment]
Yes, I'm aware of the issue. Thank you.
