### ISSUE TITLE
"Sort alphabetically" no longer seems to work

### ISSUE THREAD

**Issue by beltsonata** [odebroqueville/contextSearch#181]
Clicking on the button does nothing, and the JS console shows:

```
Uncaught TypeError: searchEngines[id] is undefined
    sortSearchEnginesAlphabeticallyInFolder moz-extension://c7561841-418e-4605-91da-3cdbffbf82b9/scripts/options.js:926
    sortSearchEnginesAlphabetically moz-extension://c7561841-418e-4605-91da-3cdbffbf82b9/scripts/options.js:944
26 options.js:926:17
    sortSearchEnginesAlphabeticallyInFolder moz-extension://c7561841-418e-4605-91da-3cdbffbf82b9/scripts/options.js:926
    sortSearchEnginesAlphabetically moz-extension://c7561841-418e-4605-91da-3cdbffbf82b9/scripts/options.js:944
```

![image](https://github.com/odebroqueville/contextSearch/assets/88738/610fcf23-b2b8-47bc-ad7c-ad4cf161e0ce)

**Comment by odebroqueville** [comment]
Sorry for the belated response and thank you for bringing this bug to my attention. A fix will be released shortly.

**Comment by beltsonata** [comment]
Many thanks!

**Comment by odebroqueville** [comment]
Release 5.0.6 should fix things. Release 5.0.7 will remove separators if search engines are sorted alphabetically.

**Comment by beltsonata** [comment]
Nice one, I can confirm this has fixed it.
