### ISSUE TITLE
Download Video menu item appearing randomly

### ISSUE THREAD

**Issue by airone506** [odebroqueville/contextSearch#183]
There seems to be an issue in the latest version 5.0.6. 

When no text is selected on the page, there is an item in the Firefox context menu (right click anywhere on the page), the "Download Video" text with contextSearch icon. When there is some text selected on the page, the "Download Video" text (without any icon) appears above all the search engines in the context submenu of the contextSearch. The "Download Video" seems to be doing nothing after clicking on it.

**Comment by odebroqueville** [comment]
I think I've found a fix for this. Starting from release 5.0.7, the context menu item 'Download video' should only appear when you're visiting YouTube or Vimeo websites. The nativeMessaging permission has to be enabled to video downloads to be possible. It also requires some manual configuration as explained in the extension's description page under section 'Advanced features for macOS users'.

**Comment by airone506** [comment]
I just tested the 5.0.7 version, the above described bug appears no more. Thank you for a very quick fix.
