### ISSUE TITLE
Change the keyboard shortcut to perform an AI Search using the command window 

### ISSUE THREAD

**Issue by Roald-Andresen** [odebroqueville/contextSearch#186]
Hi
Can you please provide an option for disabling this functionality?
Or, at least do something about the keyboard shortcut, since ctrl+0 already is a standard keyboard shortcut for zoom to default level.

Otherwise:  I love this extension.  Wouldn't want to use Firefox without it.

:-) Roald

**Comment by mahkitah** [comment]
Yes, please remove the ctrl+0 shortcut.
The AI window every time you reset the zoom level is very annoying.

**Comment by odebroqueville** [comment]
No problem, will change the keyboard shortcut for the command window. Would you have any suggestions because it can be a bit of a challenge to find a good keyboard shortcut that isn't already assigned?

**Comment by Roald-Andresen** [comment]
I haven't really thought about it, since the AI search functionality is of no interest to me.  Perhaps some ctrl+alt+(something) could be used, even though 3-key combos are disliked by many.  If I were to use it, I would have preferred menu item option instead (perhaps context menu item).

**Comment by max221** [comment]
I'm also not interested in the AI search. The ctrl+0 is making me nuts. Please please find an alternative shortcut for it.

**Comment by skippdiddly** [comment]
I love and use your extension everyday and I agree it's generally quite a challenge to find a new keyboard combo that isn't already used, even a 3 term combo. 

Would it be possible to place an option in right click menu to 'Search AI', along with the other options: 'Multiple search engines search', etc.?  As a user, these options are very accessible to me, and would eliminate the issue of keyboard shortcut discrepancies for users in general.

**Comment by ymmv99** [comment]
I came across this unexpected new feature today. I'd like to turn it off too. Can't you add an option for people to turn this off or create a keyboard shortcut of their own choosing?

**Comment by odebroqueville** [comment]
In v5.2.0 I've changed the keyboard shortcut to Ctrl+Alt+0 for Windows and Command+Alt+0 for Mac. I hope this won't turn out to be a nuisance for users. I've also added an option to open the AI Search window from the context menu. If the keyboard shortcut still is a problem then I'll remove it, but I know some users like to be able to navigate entirely from their keyboard.

**Comment by Roald-Andresen** [comment]
Excellent!  I'm happy with that.  Thanks!

**Comment by ymmv99** [comment]
Problem solved!

**Comment by skippdiddly** [comment]
Very good!  Thank you!

**Comment by Roald-Andresen** [comment]
It may be unrelated, but the context search menu disappeared after the latest update.
Simple workaround:  Any small change to the list of search engines brings the context menu back (I guess it is recreated when changes happens)

**Comment by odebroqueville** [comment]
Some Windows users have been reporting issues after the last update. It's namely been reported here: [https://github.com/odebroqueville/contextSearch/issues/189](https://github.com/odebroqueville/contextSearch/issues/189)

I'd greatly appreciate if any of you can help me debug under issue #189 as I don't have a Windows machine. Many thanks in advance.

**Comment by ymmv99** [comment]
Ah, I got the “plugin is slowing Firefox” popup just a minute ago. So you don’t see this issue immediately after updating.


Saskia
