### ISSUE TITLE
Can the sidebar be displayed on the right side of the browser?

### ISSUE THREAD

**Issue by Benson1997** [odebroqueville/contextSearch#187]
The plugin is very useful, thank you very much for your hard work! 
The sidebar in Firefox always displays on the left side, which covers the tabs on the left. 
Can the sidebar be displayed on the right side of the browser?🌹

**Comment by odebroqueville** [comment]
@Benson1997 Dear Benson, thank you for your kind note. Not everyone recognises how much work goes into making such an extension, so I appreciate. AFAIK it's not possible to programmatically set the sidebar to open on the left or right. This is entirely decided and set manually by the user. Once you've opened the sidebar, select the drop down menu to select the option to "Move Sidebar to Right". I believe the settings remains unchanged until you manually change it yourself again. I hope this helps! Don't hesitate if you have any other questions.

![CleanShot 2024-08-17 at 17 11 40@2x](https://github.com/user-attachments/assets/6b88ab1e-ec29-45ca-936f-c807ffdae727)
