### ISSUE TITLE
Update Breaks Extension

### ISSUE THREAD

**Issue by Lynx560** [odebroqueville/contextSearch#189]
The 18 August 2024 update removed the extension from the Context Menu.

I am running Firefox 129.0.1 on a Windows 10 (22H2) machine.

A few minutes after I opened Firefox this morning, I was notified that ContextSearch was slowing down Firefox (similar to "A webpage is slowing down Firefox). The only option in the given was to shut the extension off. Since I did not want to do that, I restarted Firefox to see if the problem would stop.

After restarting, I got the notification again and then noticed that the ContextSearch menu listing was missing !!!

I opened the FF Extension Page (about:addons) and saw that the Extension was still running (not shut off ?!?), but the menu was still not there !!! I then opened Options under the ContextSearch listing to see if anything had changed, but there was nothing that I could find...

Fortunately, I use an app to backup Firefox (Hekasoft backup & Restore) and was able to restore to an earlier point.
Unfortunately, the same thing happened again !!!

I had NO IDEA why this was happening.... until I noticed ContextSearch had just updated.
[I should say that I have always allowed Context Search to auto-update in the past...]

I turned off my internet connection & restored Firefox (so ContextSearch would not update)
I then opened Firefox and opened the Addon/Extension page.
I selected "Manage" under the extension & scrolled down to the "Allow automatic updates" and selected "Off" 

After [u]hours[/u] of trying to find the problem, I can report that shutting off updates fixed the problem.

Hopefully this issue will be corrected soon so I can allow it to update automatically.

Here is an image of my current ContextSearch info:
![2024-08-18_235053](https://github.com/user-attachments/assets/62b69f64-780c-4ff1-987c-5d2c2a6102aa)

**Comment by odebroqueville** [comment]
Thank you for taking the time to report this issue. I honestly don't know what's causing this issue as I haven't encountered it on Mac and don't have a Windows machine to test things. Can you please do me a small favour:  first ensure that you've exported/ downloaded your list of custom search engines for safety (you need to enable the Downloads permission for this). Then please remove the extension from Firefox. Download (or if you're familiar with Git, clone the Context Search repo) the code from the Context Search repo on GitHub. Then, in Firefox, please visit about:debugging > This Firefox > Load Temporaryy Add-on..." and select the manifest.json file from the folder where you downloaded or cloned the CS repo. Finally, please click on the "Inspect" button which will open a new window. Visit the Console tab and please report any errors you see. This would be very helpful for me to debug.

**Comment by ymmv99** [comment]
I didn't have this problem. The update works without problems on my PC (Windows 11 Enterprise with Firefox 129.0.1

**Comment by bugraonalan** [comment]
Hello @odebroqueville ,

I am facing the same problem as @Lynx560 . I applied the parameters you requested in your answer in this thread. Below are my system and CS extension information, as well as the information in the "console tab" you requested. I am waiting for your support and comments, if there is anything else you want to solve the problem, I can send it.

Again, in your comment above, you wrote "ensure that you've exported/downloaded your list of custom search engines for safety". I hope you said this not as a problem-solving step but to keep your own data safe? And as seen in the _disabled_export_options.png_ file, I couldn't export the search engines. I couldn't find any settings in the menu for "Download permissions" that you mentioned. If you think this is causing problems, you can mention it in your reply. I can follow any instructions you wa
![info_winver](https://github.com/user-attachments/assets/e38fbbdf-3964-4670-8f68-16fdfe72f18e)
![disabled_export_options](https://github.com/user-attachments/assets/541222f8-97ee-4740-8b84-b94e6131b7c1)
![info_cs_console_tab](https://github.com/user-attachments/assets/57e8f1e4-fd00-41ce-ad84-2465b406e15a)
![info_cs_engines_mainpage](https://github.com/user-attachments/assets/1129b2f1-8b4e-4f99-81f0-419b9e970269)
![info_cs_extension_page](https://github.com/user-attachments/assets/b7465455-8bef-4fcc-b47e-dfd46f4671be)
![info_manifestjson_from_repo](https://github.com/user-attachments/assets/6c5378c4-ae2a-4c12-a11a-2be1a4393dca)
![info_mozillafirefox_ver](https://github.com/user-attachments/assets/063a9d82-db67-4042-86f2-f820ce36b4e9)
nt on this.

Best

**Comment by bugraonalan** [comment]
[2] Finally, I applied the steps about:debugging -> Inspect -> See console tab on **Firefox Developer Edition 130.0b6 (64-bit).** Here are the debugging results, I hope it will be useful for you.

![image](https://github.com/user-attachments/assets/5006864d-191d-4cb3-9914-21734f9e9793)

**Comment by Alka1n** [comment]
Hello @odebroqueville ,

I am facing the same problem as @Lynx560. "ContextSearch was slowing down Firefox" appears when opening a photo in WhatsApp Web.

**Comment by Lynx560** [comment]
@odebroqueville 

My apologies, but I am nowhere near computer savvy enough to perform the steps you ask for.

I will wait to see if the others that have the same issue are able to fix the problem.
If so, I will re-enable auto-updates.

Thank you for getting right on top of this !


PS: I love ContextSearch. I use it everyday to search everyday. I hope this issue is fixed soon :)

**Comment by ymmv99** [comment]
Ah, I got the “plugin is slowing Firefox” popup just a minute ago. So you don’t see this issue immediately after updating. The Context Search menu was also gone - until I changed a minor setting and it reappeared.

**Comment by 613TheEvil** [comment]
I have the same problem, I noticed today, damn automatic updates... The context menu disappeared. And I can't save the search engines, my button is also greyed-out. If I uninstall the add-on and try to install an older version somehow, I would have to add them all manually, again. And one more thing, I could not contact you or even leave a review on Firefox's add-ons website, that's strange. I am logged in.

**Comment by max221** [comment]
Same here. Firefox 129.01 64bit; Windows 11 Pro 64bit (23H2). Latest context menu disappeared for me, too. Went back to 5.1.2.

**Comment by pvones** [comment]
I can also confirm the slowing down notification. Mostly on web site like Facebook.

**Comment by Lynx560** [comment]
> Ah, I got the “plugin is slowing Firefox” popup just a minute ago. So you don’t see this issue immediately after updating. The Context Search menu was also gone - until I changed a minor setting and it reappeared.

Can you please let us know what the "minor setting" was ?

**Comment by voxel3** [comment]
Same problem: the context menu is missing, but apparently there are no slowdowns.
I managed to get the menu back (temporarily) by disabling/enabling the search engine (I only use one) in the preferences. It doesn't work if you do it (globally) from about:addons.
But this seems to cause some sort of “duplication”. When I do a search I get 2 new tabs with the same result. If I disable/enable it again and do a new search I get 4 tabs and so on.
If you restart Firefox again it doesn't appear anymore.

**Comment by ymmv99** [comment]
> > Ah, I got the “plugin is slowing Firefox” popup just a minute ago. So you don’t see this issue immediately after updating. The Context Search menu was also gone - until I changed a minor setting and it reappeared.
> 
> Can you please let us know what the "minor setting" was ?

I changed the order of one of the search entries in the list.

**Comment by highflux7** [comment]
Same thing, linux firefox v120.0. Context Search menu missing after update.

**Comment by jrom99** [comment]
Same here on Firefox v129.0 for Fedora linux, extension version 5.2.0.

I can confirm that changing the order of providers makes the context menu reappear.

Toggling the checkbox "Display the search results after the last tab" doesn't seem to work after this, though. But after I disabled it, the extension started opening three tabs whenever I clicked to search. I'm not sure if this behavior is due to how many times I deactivated or how many times I clicked to search before un-toggling the checkbox.

**Comment by mikdeb** [comment]
Firefox ES v115.14 on Debian Bookworm.
Mostly the same behaviour here as jrom99 described:
Changing the order of providers makes the context menu reappear.
The extension started opening two (not three) tabs whenever I click to search.

**Comment by kapitainsky** [comment]
The same as others but on macOS - both Firefox and macOS latest releases.

**Comment by jamesdeluk** [comment]
Up-to-date Firefox and Windows 11. I seem to only get the "slowing down" warning about CS on web.whatsapp.com - which other extensions have also caused in the past. So I'm gonna blame Meta, because why not. Otherwise, I haven't noticed the menu disappear, and it only opens a single tab when searching - in other words, works as expected.

**Comment by TitLait** [comment]
Seeing similar problems (context menu being gone at times), with the extensions slowing pages to the point of Firefox proposing stopping the extension.

Firefox v129 on Windows 11 23H2

**Comment by WildBillDoE** [comment]
I get the same warnings about slowdowns but only on Facebook every time I visit. Win 10 FFv129

**Comment by odebroqueville** [comment]
Sincere apologies to all of you encountering issues with the last update. I've removed it from AMO and reverted to the preceding v5.1.2. I'll make a quick release to v5.1.3 for those annoyed by the CTRL+0 shortcut and will test more thoroughly before I update again to v5.2.0.

**Comment by 613TheEvil** [comment]
Bravo! We knew we could count on you.

**Comment by jamesdeluk** [comment]
Isn't it stopping the extension that causes the menu to disappear? Would make sense.

WillBillDoE's also experiencing the issue on Meta-owned platforms. Maybe that's a link?

**Comment by odebroqueville** [comment]
Again, so sorry to all of you, especially those who have made a kind donation (thanks Mike!). I had tried to improve the code by refactoring parts of the background script, but I obviously must have overlooked something.

PLEASE ALL REVERT TO VERSION 5.1.2 but ensure you have EXPORTED/DOWNLOADED A COPY OF YOUR SEARCH ENGINES BEFORE THAT.

**Comment by alan-2001** [comment]
I am devastated to report that mine is broken too! 

I've tried adding and removing it, nothing seems to work. I know you're working on it Olivier but I thought I'd chime in as well. I've saved my settings so they're safe. Hope we get a fix soon, life without this add-on is pretty shit! 

Linux Mint 21 with Firefox 124.0.2 (64-bit)

Thanks :-)

**Comment by jamesdeluk** [comment]
Not sure if this is replaced but now when I click the extension from the extensions menu on the toolbar
![image](https://github.com/user-attachments/assets/f300bd41-1ebf-4cc7-ae8d-11db7c295a8e)
instead of the settings, I get the AI search. So the only way to access settings is with `cs .` it seems

**Comment by odebroqueville** [comment]
Version 5.2.1 has just been released. It's a copy of version 5.1.2 with a minor change: the shortcut to open the AI Search window has been changed to 'Ctrl+Alt+0' for Windows users and 'Cmd+Alt+0' for Mac users. Hopefully, things will come back to normal with v5.2.1 whilst I investigate what went wrong with v5.2.0.

Thank you all for your patience and understanding.

**Comment by AymondoX** [comment]
Thanks a lot. Version 5.2.1 working fine on iMac now

**Comment by negura2585** [comment]
Thanks! It's working fine on Windows 10 as well now.

**Comment by odebroqueville** [comment]
@Alka1n What do you mean by opening a photo? Are you doing a Google reverse image search or Google Lens search?

**Comment by Alka1n** [comment]
@odebroqueville In WhatsApp web, in any dialog, click on any photo with the left mouse button, it should open in an enlarged form, at this moment firefox displayed “ContextSearch was slowing down Firefox”. Everything is fine in version 5.1.2.
