### ISSUE TITLE
Context Search disappeared from the menu entirely since v3.71

### ISSUE THREAD

**Issue by MikhailAristov** [odebroqueville/contextSearch#19]
Since today (so I think, v3.71), I've noticed that my search engine list in the context menu is empty. After restarting Firefox (v66.0.2), Context Search disappeared from my context menu entirely. Removing the addon, restarting browser, and installing it again didn't help.

So... help? Thanks in advance.

**Comment by MikhailAristov** [comment]
Just as I posted it, the menu item came back. My guess is that it's because I've offhandedly tried re-importing my custom search engine list -- so it's probably another form of issue #14, since after re-starting Firefox, the menu item was still visible, but no search engines were present. I am closing this for now.

**Comment by planket2** [comment]
I am having the exact same issue. .Right now i cannot see the list in the context menu from right clicking. its dissapeared. i tried restarting Firefox, but nothing. I tried unchecking "Display favicons in context menu list"  but when restarting Firefox it shows thats auto ticked again. Still not appearing.  Please can you fix this? i dont know whats going on but cant get it to show in the "right click" menu anymore.  However my custom search engines are still there.

**Comment by Djeremaille** [comment]
Same. Not appearing in the right click menu.

**Comment by odebroqueville** [comment]
I'm experiencing the same. Trying to find the cause and solution. I've asked support from MDN.. if someone more proficient could help debugging, but nobody seems to have the time! In the mean time, I may only recommend using another similar extension: 
https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/ 
because I don't know how long it'll be before everything gets fixed.

**Comment by MikhailAristov** [comment]
@planket2, @Djeremaille: Have you tried my workaround of exporting and re-importing the search engines. It works for me consistently. You must do it every time you close and open Firefox, but I don't really close the browser any more (because of an unrelated issue), so it's almost no difference to before, as I keep my exported search engines on my desktop.

**Comment by didli** [comment]
Same here with FF66.0.2, except I don't have to export/import the engines, I just have to save the conf file on disk (the option below import/export) and the menu is back with the full list. It's still annoying, but that's it.

**Comment by agoree407** [comment]
Another "me too," however @didli's workaround worked for me as well, thanks man!

**Comment by odebroqueville** [comment]
Please let me know if the latest release 3.72 fixes things for you. Thank you.

**Comment by MikhailAristov** [comment]
Yup, the engines show up in the context menu as normal after restarting Firefox. Seems fixed to me, thanks a bunch! :-)

**Comment by didli** [comment]
Confirmed, 3.72 fixed the issue. Thanks a lot.

**Comment by planket2** [comment]
thanks all good here!

**Comment by odebroqueville** [comment]
Thank you all for your patience.

**Comment by MikhailAristov** [comment]
@odebroqueville: No, thank _you_, for your fast and effective response.
