### ISSUE TITLE
Single search opens multiple tabs

### ISSUE THREAD

**Issue by rgoubet** [odebroqueville/contextSearch#190]
After reinstalling the extension, and re-importing my search engines from a JSON export, any search on a selection opens the same search in 3 tabs.

I tried again reinstalling, then resetting all preferences, then re-importing my search engines, and it then started opening 6 tabs, then 12 tabs!!!

I'm using Firefox 129 on Ubuntu 24.04.

**Comment by TitLait** [comment]
Same thing here.
Firefox 129 on Windows 11 23H2.

**Comment by odebroqueville** [comment]
Thank you for reporting this. It's actually caused by the 5.2.0 update and therefore is a duplicate of #189 . Please kindly revert to v5.1.2 whilst I investigate further. Sincere apologies for the trouble.
