### ISSUE TITLE
Sidebar opens on each new search

### ISSUE THREAD

**Issue by kapitainsky** [odebroqueville/contextSearch#195]
After I have installed the latest v5.3.1 every time I use context search I have empty side bar opened. Below picture shows very well how ugly it is. For aesthetic and many other reasons I do not want it:)

<img width="1421" alt="Screenshot 2024-10-30 at 4 41 32 pm" src="https://github.com/user-attachments/assets/4ac71d11-49f4-4156-b75b-04ed0a565569">

Of course I can close it. But next time I search something using this wonderful add-on it pops up again... 

Definitely not something I wish.  I have spent long time trying to find an option to turn it off - to no avail. Maybe I am just blind in this case.

Here my settings:

<img width="518" alt="Screenshot 2024-10-30 at 4 59 34 pm" src="https://github.com/user-attachments/assets/80d8957f-578b-475f-9769-109f2402ea66">

I would like my searches to open in new tab - like always before. They do now too but with addition of this side bar appearing out of the blue.

All is happening on macOS 15.1 and Firefox 132.0

I would be grateful if somebody can shed a light on how to get rid this side bar. 

I have been using contextSearch for ages (many many years) and never had such issue before.

**Comment by odebroqueville** [comment]
I know why this is happening: the makers of Firefox only allow us to open the sidebar following an action, e.g. a click on an item in the context menu. Unfortunately, for details you may not understand, it's not possible to only open the sidebar when the sidebar option is selected in the options. It's all or nothing: either I always open the sidebar or I always keep it closed. You're happy in the latter case and others will complain or think that the extension isn't working! What to do?!

**Comment by odebroqueville** [comment]
Instead of opening search results "In a new tab" as you selected above, you can choose to open them "In the sidebar". Give it a try.

**Comment by kapitainsky** [comment]
Thank for your suggestion but it is pointless in the way how I use (and used for years) this add-on. I want to open be it Wikipedia, Amazon or Google maps.  How you think you can work with maps in sidebar? or continue shopping on Amazon?

To be 100% clear what is happening now:


https://github.com/user-attachments/assets/80ea2c69-b00b-4b3e-9042-70b760cb8434

It is disaster:)

**Comment by kapitainsky** [comment]
I have tried to use side bar. For example when using Google maps search it even does not open maps (new tab does) but text results of geographical term search.

It is of course your add-on and you decide how it works. But I can not believe that I will be only one complaining. It break mine and many others workflows.

Maybe two versions of add-on are really an option?

**Comment by Vingolf** [comment]
**Off topic:**
Hi Olivier 😃
my main interest here is to say **thank you** that your addon is back online 👍

A short comment on this issue, althoug I am not too much in to it:

> It's all or nothing: either I always open the sidebar or I always keep it closed. 
You're happy in the latter case and others will complain or think that the extension isn't working! What to do?!

I always use context search in an new tab, so I would be happy, if the sidebar will always be closed 😉

[kapitainsky](https://github.com/kapitainsky) wrote:
> Maybe two versions of add-on are really an option?

In a earlier Version Context Search v.5.2.1 in FF 130esr on Windows 10 I have not encountered this issue.
The search result appears in a new tab without opening the sidebar.

Perhaps an option for you is to use a previous version 🤔

Vingolf

**Comment by kapitainsky** [comment]
> Perhaps an option for you is to use a previous version 🤔

If nothing can be done than 100% this is what I will do. Any idea how to install older versions?

**Comment by odebroqueville** [comment]
I think I have found a solution for the sidebar to only open when it's been selected in the options page. Please bare with me until I finish testing things. It'll take a couple of days. Thanks.

**Comment by odebroqueville** [comment]
Please update to version 5.3.2 (just released). It should fix things. Let me know.

**Comment by kapitainsky** [comment]
Update on my testing. When 5.3.2  works then all is perfect... but after few hours right click contextual menu to trigger search disappears.... gone.. just like that. No fiddling with options not any browser settings. Only way to restore it is to remove add-on and install it again. But then after few hours the same happens.

I have no idea what the culprit is. All started with Firefox update to v132.0 and coincidently at the same time contextSearch update to 5.3.1 (5.3.2 now). Before I used always updated contextSearch add-on for years on always kept up to date Firefox. Never had slightest issues but some glitch once I think (fixed in days).

**Comment by kapitainsky** [comment]
And it is not all. Looks like for some bizarre reasons (when everything works) very often add-on triggers searches not for selected word but for some word which was searched much earlier...

**Comment by odebroqueville** [comment]
Oh dear, what a nightmare! There's something strange in your screenshot: the keyboard shortcuts shouldn't be "undefined". Are you on Windows? (I haven't experienced this on Mac) Another Windows user reported that Context Search wouldn't show up in the context menu, so there definitely is an issue. What bothers me is that I can't test on Windows. Maybe I shouldn't have brought the extension back on AMO!

**Comment by kapitainsky** [comment]
> There's something strange in your screenshot: the keyboard shortcuts shouldn't be "undefined". Are you on Windows?

It was from my old json import. Suspecting that it might be an issue I now started fresh - unfortunately the saga of weird behaviours continue. I am not sure if issue is with your add-on or there is something else in play here. But again I never had any issues - all started now with new Firefox and new add-on.

**Comment by odebroqueville** [comment]
I was able to reproduce a bug: restarting Firefox removes CS from the context menu. I'm really sorry for the trouble. I'll investigate further tomorrow as it's getting late on my end.

**Comment by kapitainsky** [comment]
> I was able to reproduce a bug: restarting Firefox removes CS from the context menu. I'm really sorry for the trouble. I'll investigate further tomorrow as it's getting late on my end.

No worries. I do understand that It always takes time to iron rough edges. Not only in programming.

I appreciate your work on this add-on.

**Comment by odebroqueville** [comment]
Thank you for your understanding. Just so you know that I'm trying to find a. solution, it would appear that the bug is coming from the latest Firefox updates: https://discourse.mozilla.org/t/how-to-test-debug-what-happens-on-browser-quit-and-restart/136864

**Comment by kapitainsky** [comment]
5.3.3 installed. Feedback will follow this weekend.

Now I understand why I quickly noticed that context menu is missing. My Frefox restarts quite often - actually it is automated (periodic launchd script) whenever my mac tries to sleep and Firefox holds some sleep preventing assertions - which is one of the macOS Firefox issues not fixed for many years.

Let's hope that now all will be fine with add-on. I will now soon:)

**Comment by kapitainsky** [comment]
Good news first - context menu does not vanish anymore despite multiple Firefox restarts. Also have not noticed searches triggered with some old values.

Now bad news - encouraged by progress so far decided to customise search engines layout to my liking - hide some, add some new, move things around. Initially all went very well but good things rarely last forever:) All is gone (and returns to default) after some Firefox restart. Hopefully it is related to the same problem as disappearing context menu and should not be impossible to fix.

**Comment by kapitainsky** [comment]
IMO "Sidebar opens on each new search" issue is fixed and I am closing it. To keep things clean if I encounter any other issue I start new thread.

Thank you very much for keeping this add-on alive and sound.

**Comment by odebroqueville** [comment]
@kapitainsky maybe the reset checkboxes should bee cleared after a reset. What do you think?

**Comment by kapitainsky** [comment]
> @kapitainsky maybe the reset checkboxes should bee cleared after a reset. What do you think?

IMO for sure this should be how it works with existing checkboxes and one button design. I doubt anybody suspects that selected box implies reset every time Firefox restarts. It is, I think, naturally one off action - reset something to start fresh.
