### ISSUE TITLE
bug autostart

### ISSUE THREAD

**Issue by snipdomenico** [odebroqueville/contextSearch#2]
The contextSearch is not 'loaded' every time the browser is started. In order to make the contextSearch appear in the context menu, it is needed to go into the addon page of the browser and change a value.

Verified on Firefox 61.0.1 (64 bit)

**Comment by kuality** [comment]
ContextSearch doesn't seem to be autostarting on several computers I support either. Some of these are in a workstation managed setting, but this is happening on my home PC as well.
FF 63.0.3 Windows 7

**Comment by odebroqueville** [comment]
Are you still experiencing this issue with the latest release 3.72?

**Comment by kuality** [comment]
It looks like it is no longer a problem on any of my PCs. I can’t remember if I had done anything to tweak it to work. Happy that this is working again, I use ContextSearch a lot!

**Comment by odebroqueville** [comment]
Good to hear that things are working now. I'll be closing the issue now. Don't hesitate to re-open if the problem arises again. Have a great day!
