### ISSUE TITLE
ContextSearch Reset Bug

### ISSUE THREAD

**Issue by McArtichoke** [odebroqueville/contextSearch#21]
I recently purchased a new Acer laptop to replace my old HP, in which ContextSearch worked fine.  Now though, it seems to happen daily this week, I have added my three favorite search engines and ALL DISAPPEAR after apparently being reset.  I hate having to re-add them on a daily basis.  I did uncheck the three boxes under "Reset Options."  I'm not yet sure if that was a fix.

**Comment by odebroqueville** [comment]
The reset button still is buggy, but if you refresh the Options page, then you should see your search engines appear without having to add them again! I think it's just a refresh issue and I'm looking into it. Let me now if your search engines appear after refreshing the options page.

**Comment by McArtichoke** [comment]
Problem solved!  Thank you, sir, for your assistance.
McArtichoke
 
 
-----Original Message-----

**Comment by odebroqueville** [comment]
You're welcome.
