### ISSUE TITLE
Option to renounce of cs qualifier in omnibox

### ISSUE THREAD

**Issue by grossherr** [odebroqueville/contextSearch#23]
Maintaining two lists of search engines, so the list of search extensions by FF itself and the CS list, for the most part doesn't make a lot of sense, to me at least. It would be amazing to have an option to renounce of the `cs` qualifier in the omnibox, making it possible to just use the keywords.

**Comment by odebroqueville** [comment]
I don't believe that's possible, because there has to be a way for the extension to know when you're addressing it. Maybe what you really need is the possibility to import your search engines from ffx to CS.

**Comment by grossherr** [comment]
I still would type in the qualifier for the search engine of course. Staying with the example from the readme, instead of `cs w atom` I would only type `w atom`. 

I can have that of course, if I add the addon for the wikipedia search to the on-click search feature, and give it the keyword w, but then again I have to maintain two lists of search engines. The flexibility of CS, especially because you can add any site by URL, is what I like though. Which is why I'm personally not that interested in importing from Firefox to CS. 

Anyhow, I just thought there might maybe be a relatively easy way to use the keywords set by CS without the additional cs. 

This probably can be closed then. Thanks for looking into it and the great extension.
