### ISSUE TITLE
Two bugs in latest build

### ISSUE THREAD

**Issue by marty60** [odebroqueville/contextSearch#24]
There are two bugs in the latest build v3.19 regarding opening in the same tab:

1.) When highlighting text then doing a search in about:support there is no response.
2.) When first starting the browser searching from web pages when highlighting text opens a new tab regardless of the setting. Only when going to the Options page first does it then start opening in the same tab correctly. 

Please take a look to see if you can reproduce.

**Comment by marty60** [comment]
The first issue is fixed in v3.20 but the second bug is still there. It's not saving the settings when you open results in the same tab or window. You have to go to the addons page each time you restart the browser and reset it.

**Comment by odebroqueville** [comment]
Thanks for reporting this bug, marty. Please check if release 3.21 fixes the bug for you. If so, then I'll close this issue. Cheers mate.

**Comment by marty60** [comment]
Was v3.21 updated to fix the second bug because it's still defaulting to "in a new tab". If you close the browser or restart it you have to go to options and reset it otherwise searches open in a new tab . 

The option to make the new tab or window active is fixed.

**Comment by odebroqueville** [comment]
I think and hope we've ironed it out in v3.22. Will do some more testing tomorrow. Thanks for following up on this issue, marty. Well appreciated.

**Comment by marty60** [comment]
To the developer: v3.22 working good here, you can probably mark this as closed. 

Nice job on this addon, it's shaping up as an excellent WE replacement.
