### ISSUE TITLE
Change item order in the context menu

### ISSUE THREAD

**Issue by Ietek** [odebroqueville/contextSearch#25]
Is it possible to change the order of the item 'Context Search' in the context menu? It would be great if it was under the default item 'Search Google for'.

I had another search add-on in this position and it was very comfortable.

**Comment by odebroqueville** [comment]
I don't think it's possible any more. At least, I haven't found any documentation on MDN or elsewhere explaining how to do this. Just to make sure, though, I have posted the question on [Mozilla Discourse](https://discourse.mozilla.org/t/how-to-set-position-of-context-menu-title/40799).

**Comment by odebroqueville** [comment]
I'm closing the issue as it has been confirmed on Mozilla Discourse that your request may no longer be met. Sorry!

**Comment by Ietek** [comment]
The add-on that I was talking about is this: https://legacycollector.org/firefox-addons/3803/index.html

Maybe you can see how the author changed the position.

Thank you.

**Comment by odebroqueville** [comment]
You can read on their website:
"Mozilla has removed all "legacy extensions" from their add-ons site in November 2018, leaving many users of older "long term support" versions of the browser, as well as browser forks, dead in the water."
As of November 2018, Mozilla . introduced a new API to create web extensions. This new API doesn't have all the same features and functionality as the previous one. It is no longer possible to position the title of an extension in the context menu. You may try and post a feature request with Mozilla to make the feature available with the new API, but in the mean time, there's nothing I can do.
