### ISSUE TITLE
i cant add

### ISSUE THREAD

**Issue by deviant2** [odebroqueville/contextSearch#27]
(Which search engines would you like to appear in the context menu or grid? ->Add a new search engine button)
i cant add search engine

win10x32 ff ESR 52.9.0 x32
context search ver : 3.72, 3.69

**Comment by odebroqueville** [comment]
Context Search uses Mozilla's Web Extensions API introduced end 2017 and supported by Firefox 57 and above. Unfortunately, Firefox 52 isn't supported.
