### ISSUE TITLE
Please allow shift+click feature to be disabled or remapped

### ISSUE THREAD

**Issue by Sarkos** [odebroqueville/contextSearch#3]
I sometimes use shift+click to select large blocks of text, and this addon interferes with that.

**Comment by PeterBurner** [comment]
same here
its pretty annoying

**Comment by odebroqueville** [comment]
Sorry for the late response. I'm working on the code to use an alternative key combination to launch the grid of icons. Hang in there!

**Comment by odebroqueville** [comment]
Shift-click is now replaced by Alt-click.

**Comment by monoblaine** [comment]
<kbd>Alt</kbd> + click is actually used to highlight text within links without clicking them. Can you add an option to disable this shortcut?

**Comment by cjscheller** [comment]
@odebroqueville Implemented in #48  ... take a look and let me know your thoughts
