### ISSUE TITLE
Using "Multiple search engines" opens new window, not tab, Firefox

### ISSUE THREAD

**Issue by chaffinched** [odebroqueville/contextSearch#30]
Hi, 

I was expecting this to open all of the results in new tabs, but instead it opened a new window and put all of the tabs there. Is this expected behaviour, and / or how can I change it to tabs only? 

Firefox 68.0.2, 64-bit, Windows 10.

**Comment by odebroqueville** [comment]
It is the expected behaviour because it's cleaner and more structured. There's no option to change this behaviour and I regret but I no longer have the time to further develop or modify any extension. Nothing's ever perfect I guess!
