### ISSUE TITLE
Replace up & down functions on the Options page by drag & drop functionality

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#31]

**Comment by cjscheller** [comment]
@odebroqueville Happy to tackle this. Do you prefer vanilla JS or are you ok with using a library such as https://github.com/SortableJS/Sortable?

**Comment by odebroqueville** [comment]
Hi @cjscheller ! You're most welcome to give it a try. I have no problem using a library as long as it isn't too large and integrates smoothly in the web extension. As a hint, I believe you'll have to be working mostly on the file options.js. Let me know if you have any questions.

**Comment by odebroqueville** [comment]
@cjscheller Vielen Dank!
