### ISSUE TITLE
Reseting with 'force reload default search engines' fails to refresh completely

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#35]
**STEPS TO REPRODUCE**:

1. Open the extension's Options page, i.e. the extension's Preferences page.
2. Remove any search engine from the Options page by clicking on a trash can.
3. Click the 'Reset' button under 'Reset options' (from the Options page) after having checked 'Force reload of default search engines list'.

Reloading the Options page should display the complete list of search engines.

**Comment by odebroqueville** [comment]
@cjscheller Are you using VS Code along with the Debugger for Firefox extension? On my end, in the debug console, at a certain point in time, the debugger complains that list[id] is undefined in sort.js.

**Comment by odebroqueville** [comment]
Hi Carl @cjscheller , I believe there's a problem in the function restoreOptionsPage() in options.js and that listSearchEngines(data) gets called before browser.storage.sync.get(null) has completed. It's as if 'await' isn't having any effect. Can you please have a look at the restoreOptionsPage function and tell me if you spot anything wrong?

**Comment by cjscheller** [comment]
@odebroqueville Not using VS Code, but I am seeing the same error when inspecting the extension background directly - `list[id] is undefined` at `sort.js:15`. It seems that on reset (init()), sortByIndex is being called twice and the first time it appears to run when searchEngines list is uninitialized ({amazon: undefined, ask: undefined, etc.}).

However, I don't feel like this error is causing the issue. I agree with you that it appears to be a timing issue related to options.js attempting to initialize the search engine list before it is finished being set in browser storage from the background script. I'll need to spend more time investigating the flow when I am free later on.

**Comment by cjscheller** [comment]
@odebroqueville Just registered, should be available now.

**Comment by cjscheller** [comment]
Added a PR to resolve this issue. The issue was that the reset functionality was resolving and sending a response to the options page before the search engine list had actually finished getting stored to browser storage in `saveSearchEnginesToStorageSync`. I moved the logic into the resolution of that function and it is now working consistently for me. 

Also - it appears that the `sortByIndex` function is defined twice in the same scope, once in background.js and once in sort.js. I believe the function in background.js is not being used as it is being overwritten by the function definition is sort.js, which is loaded second. As a result I have removed the function from background.js - please let me know if you think this was an error and I can backtrack it.

**Comment by odebroqueville** [comment]
@cjscheller you definitely deserve your Hacktoberfest t-shirt! Btw, are you a software engineer? For how long have you been developing in JS?

**Comment by cjscheller** [comment]
@odebroqueville Thanks! I am happy to help and enjoying working on and using your extension. 

I am a software engineer based in USA in south Florida, and I've been developing in JS for about 3 years now. How about you?

**Comment by odebroqueville** [comment]
@cjscheller I'm a Supply Chain Coordinator based in Geneva, Switzerland, but not currently employed. I picked up programming as a hobby and, when I heard some friends on social networks worried to see their favorite extensions disappear after Mozilla introduced web extensions, I thought I would give it a try. And Voilà! I had also worked for a startup to test their WhatsApp-like application on Android and iOS. Was a bit tedious but interesting.

**Comment by odebroqueville** [comment]
@cjscheller Btw, I created a 'production' branch to remove all console logs.

**Comment by cjscheller** [comment]
@odebroqueville Sounds good. You've done a great job with the extension, especially with programming just being a hobby. Lots of users and good reviews - you should be proud! Have you ever thought about making the extension available for Google Chrome as well?

**Comment by odebroqueville** [comment]
@cjscheller Thank you, Carl. Porting the extension to Chrome is the next move. But first, I need create a separate page in GitHub for Context Search Lite. CS Lite is the same as Context Search only without the Exif Viewer (some users didn't want the Exif Viewer bundled in CS). Only problem is that I haven't been updating CS Lite since you joined, so it doesn't include all the bug fixes yet. The reason I want to sort out CS Lite before porting it to Chrome is because Chrome doesn't support the sidebar API, which is where the EXIF tags are meant to display.

**Comment by odebroqueville** [comment]
@cjscheller I created a repo for the lite version. Right now, it's not working!
https://github.com/odebroqueville/contextSearchLite

**Comment by odebroqueville** [comment]
@cjscheller just noticed the GitHub Sponsor notification and thought you may find it interesting as a potential supplementary source of income for your contribution to open source projects https://github.blog/2019-11-04-github-sponsors-is-now-out-of-beta-in-30-countries/
