### ISSUE TITLE
option to put search engines in context menu (and outside submenu)

### ISSUE THREAD

**Issue by kiuuik** [odebroqueville/contextSearch#38]
I'm using the version 3.22 (2017-10-06) from AMO in Firefox 56.

I have seen that in the last two weeks you implemented a grid layout. I couldn't test this so I don't know if this solves my problem. 

I'm coming from [Context Search X - CSX](https://addons.mozilla.org/de/firefox/addon/context-search-x/?src=search) because of the upcoming changes in FF57.

Everything works great. I miss one feature though: CSX offers to place some frequently used search engines in the context menu itself instead of the sub-menu of context search [example](https://addons.cdn.mozilla.net/user-media/previews/full/63/63955.png?modified=1415150361).

I used this to put DuckDuckGo, Google, and Google-No-Country-Redirect in the context menu. This covers about 80% of my searches. This is much quicker that using the submenu and even submenu+keys.

I think many other people do most of their searches with two or three engines. This feature might be of general interest. But I also understand if you see things differently.

Thanks for your time and great work.

P.S.: You could adjust the link in the last line of your README.md. At the moment it directs you to the french version of AMO irrespective of the browser language preferences. I adjusted it to en and then on my browser I automatically get redirected to the local version of the website. Then general site elements like "Page d’accueil du module" or "Politique de confidentialité" will be in the local language.

<pre>
    https://addons.mozilla.org/<b>en</b>/firefox/addon/contextual-search/?src=ss
</pre>

**Comment by Smile4ever** [comment]
https://addons.mozilla.org/firefox/addon/contextual-search would be an even better link for the README.

**Comment by Smile4ever** [comment]
Direct submenus are not possible with the WebExtensions API, but the grid layout will indeed be the solution for you.

**Comment by kiuuik** [comment]
Thanks for your quick help. I think I can close the issue. I'm looking forward to the grid layout. 

Maybe my original request was unclear. I guess you understood what I want but but just in case I'll try with a different wording. I don't want to take more of your time. So don't answer ...  At the moment when I want to use Context Search I highlight some text, open the context menu, move my cursor above the line "Context Search  ->", then an additional menu opens to the right. My idea was that you can make search engines appear in the original context menu so that it looks like this "search for highlighed text on DDG", "search highlighed text on Google-NCR", "Context Search  ->". 

Another minor idea: Some people might miss the option to use `%s` because it's in the middle of the readme. You could include one url that uses `%s` in the defaultSearchEngines.json or even in the example in the README.md.
