### ISSUE TITLE
Reset with 'force reload default search engines' breaks grid of icons

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#39]
**STEPS TO REPRODUCE**

1. Open the extension's options page
2. Remove a search engine (e.g. Baidu) from the list
3. Check the 'force reload default search engines' checkbox
4. Click the 'Reset' button
5. Visit a web page and test if Alt-Click is working. The grid of icons fails to display.

**Comment by odebroqueville** [comment]
@cjscheller I believe this is linked to list[id] being undefined in sortByIndex at a given point in time, but sortByIndex is used several times in background.js and once in options.js. I don't know how to determine for sure which sortByIndex is causing the problem, but I have a feeling it's the sortByIndex inside the initialiseSearchEngines function.

**Comment by odebroqueville** [comment]
@cjscheller I think the last commit fixes this bug. I had to resort to using messaging rather than a storage sync handler. Please let me know if you find that things are still broken. Have a nice weekend. I'm hoping to publish this latest version 3.8.0 of the extension to AMO next Monday.

**Comment by cjscheller** [comment]
@odebroqueville Looks good. I tested and was unable to recreate the issue, nice find and fix. 

For Javascript debugging, I primarily use the browser developer tools. Lots of console logs, reviewing the Network tab for request/response, and occasionally adding breakpoints when necessary. I've found that to be the most effective for me.
