### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by YuriiBar** [odebroqueville/contextSearch#41]
At you all works correctly, but unfortunately many searchers RU or UA of a segment web
Forcibly use encoding witht with function urlencode(), PHP
https://msdn.microsoft.com/en-us//library/4fkewx0t(v=vs.110).aspx

for example
http://hotline.ua
 or https://4pda.ru/forum
 and more...
 So the search for "телевизор" on the hotline generates http://hotline.ua/sr/?q=%D1%82%D0%B5%D0%BB%D0%B5%D0%B2%D0%B8%D0%B7%D0%BE%D1%80
 And after your application using http://hotline.ua/sr/?q=
 generated http://hotline.ua/sr/?q=телевизор 
 and the web resource does not respond with the expected result

**Comment by odebroqueville** [comment]
Implemented in version 3.5.

**Comment by YuriiBar** [comment]
Great, thanks for the implementation.
