### ISSUE TITLE
Version 3.5 prevents firefox sync from working properly

### ISSUE THREAD

**Issue by bhoppi** [odebroqueville/contextSearch#42]
After updating to the latest 3.5, when firefox syncs I get the errors as below:
Sync.Engine.Extension-Storage	ERROR	Syncing olivier.debroqueville@gmail.com: request failed: Error: HTTP 507; Error: HTTP 507 Insufficient Storage: Resource access is forbidden for this user (Maximum bytes per object exceeded (10127 > 8192 Bytes.) (resource://services-common/kinto-http-client.js:2353:21) JS Stack trace: formatResponse@kinto-http-client.js:2376:21 < processResponse@kinto-http-client.js:2351:14

which makes the firefox sync fail.
I checked the sync data and I found that there is a field called "base64" in the object which is very big. What is this?

**Comment by bhoppi** [comment]
OK, I checked the code and have known that the base64 is the favicon of the search engine. But it is too big for firefox to sync. Maybe we just need to store the favicons locally and do not need to sync them?

**Comment by odebroqueville** [comment]
Hi bhoppi,
I don't have any problems with the syncing and from what I see in your first message, it looks like the limitation comes from kinto. There might be a storage parameter you can change to increase the storage limitation. I would also be surprised if any of the base64 strings exceed 1000 bytes or characters! 10'127 bytes seems like an awful lot for a base64 string!

**Comment by Smile4ever** [comment]
@odebroqueville It's the total amount of search engines, probably. So you can exceed 8192 bytes if you are saving them all in sync storage.

IndexedDB might be the way to go.

**Comment by bhoppi** [comment]
@odebroqueville  It is the limit of Firefox that each synced item must not exceed 8192 bytes.
And you can add Baidu search engine to trigger this issue (its favicon https://icons.better-idea.org/icon?url=www.baidu.com&size=24..32..64 is oversized).

**Comment by auipga** [comment]
still present in 3.65
