### ISSUE TITLE
Sends double click when right clicking on empty space

### ISSUE THREAD

**Issue by dima6526** [odebroqueville/contextSearch#44]
Using CS 3.51 on FF developer 57.0b14, when I right click on any (also empty) space on a page it will highlight a word somewhere in the vicinity, thereby changing the available context menu entries.

**Comment by odebroqueville** [comment]
What do you mean by "thereby changing the available context menu entries"? The extension picks up the word behind the mouse pointer when you right-click without previously selecting text. It isn't supposed to do anything if you right-click on an empty space, because there's no word to select! What would you expect it to do?

**Comment by dima6526** [comment]
When I click on an empty space, a random word gets selected, one at approximately the same level on page, but some distance away, so naturally I get the context menu for the selected word and not for the empty space.

**Comment by odebroqueville** [comment]
What's the point of doing a search based on empty space!?! Sorry, but I don't get it!

**Comment by dima6526** [comment]
I am not trying to do any searches on an empty space, but I need the context menu options for empty space to be available whenever I need them, i.e. save page, save to Pocket, take screenshot and so on. They are not there because I keep getting the menu for the selected word! By the way, a like the extension very much, so it's a shame that at least on my system it seems to interfere with other functions. I think it started after the latest FF developer update a couple of days ago.

**Comment by odebroqueville** [comment]
Which viewing mode are you using? Are you using the 'icon grid' mode or the 'list' mode?

**Comment by dima6526** [comment]
List.

**Comment by odebroqueville** [comment]
Do you mean that this extension prevents other extensions from displaying context menus when right-clicking in list mode? (I'm aware of this being a problem in icon grid mode, but it shouldn't happen in list mode)

**Comment by odebroqueville** [comment]
Ah! I see what you mean! Will see what I can do about it and keep you posted.

**Comment by dima6526** [comment]
Thanks! Looking forward to getting it solved.

**Comment by bongochong** [comment]
I was just coming in to report this! Glad someone else noticed it too. It's definitely a bit annoying to have text selected when you right click pretty much anywhere on a page.

**Comment by odebroqueville** [comment]
Please test the latest release (3.52) and let me know if it fixes your issue. If you place the mouse pointer just before a space between two words and right-click, you should obtain the default context menu with your desired options. Generally, right-clicking on empty spaces should do the same.

**Comment by dima6526** [comment]
It is fixed now! However I have to agree with the author of the latest thread that it would be best to be able to disable automatic highlighting when clicking right on a word altogether. Keep up the good work!
