### ISSUE TITLE
Add an option to disable highlighting when right-click on a word

### ISSUE THREAD

**Issue by cinty8b** [odebroqueville/contextSearch#45]
This addon changes the default behavior when you right-click on a word, which I am not used to. It took me some time to find out whether it's misfunction of my mouse or an addon feature.
I recommend adding an option to disable this feature.

**Comment by cinty8b** [comment]
In addition, if any mouse gesture addon is installed and set to use right mouse button (which is default in most gesture addons), the word at the end of the trace will be highlighted.

**Comment by odebroqueville** [comment]
"I recommend adding an option to disable this feature."
-> this has been implemented in version 3.53

**Comment by odebroqueville** [comment]
The feature to select and highlight the word behind the mouse pointer when right-clicking has been dropped.
