### ISSUE TITLE
Customise cs qualifier in Omnibox

### ISSUE THREAD

**Issue by oleole39** [odebroqueville/contextSearch#45]
I have just discovered this extension which I find very interesting being until now an intensive user of similar functionnalites embedded in search engines such as Qwant or Duckduckgo. Having this functionnality be performed locally makes much sense to me.

However, I'd rather have the shortest qualifier possible - for a Wikipedia search of the word "test", in Qwant/DDG I would enter `!w test` as opposed to `cs w test` with Context Search. It is a difference of only 2 signs, but right now (slow adaptability of mine?) it feels quite much to me.

Would there be a way to:
1. Define a custom Omnibox qualifier for Context Search (change `cs` by `!` in my case)
2. Make the space sign optional after the qualifier (via a checkbox in the options tab or to remove the space the requirement of the space sign by default)
3. Forward the search term to Firefox's default search engine (SE) in case there is no matching search engine keyword due to a typo in the SE keyword or the fact that the SE is not added yet to CS preferences (current behavior with for instance `cs kwtest test` triggers a pop-up error notification and empties the address bar).   

These are actually three feature requests/enhancements that I would find valuable individually.

**Comment by oleole39** [comment]
For 1. I wonder whether it is possible to either set a variable in manifest.json file to be defined in the options tab or to modify the manifest.json file after according a value that would be entered in the options tab.

For 2. I can't comment that and fear the space is a strict requirement of Firefox.

For 3. I would appreciate any clue.

**Comment by odebroqueville** [comment]
Unfortunately, the omnibox search qualifier has to be preset in the manifest and can't be altered thereafter from a script.
