### ISSUE TITLE
Feature Request: Right&Middle-click to set alternative targets for results tab

### ISSUE THREAD

**Issue by paperboyo** [odebroqueville/contextSearch#46]
Hello,

Thank you for your work!

This is a perfect replacement for Context Search X, just one feature I miss: to be able to specify Right-click and Middle-click to alternatively open results in current/background/foreground tab. Hopefully possible within current framework.

Regards
m.

**Comment by odebroqueville** [comment]
I'm sorry but this will not be implemented in the near future as we have many other priorities.

**Comment by paperboyo** [comment]
Thanks, Oliver!

**Comment by paperboyo** [comment]
Unfortunately: https://github.com/NumeriusNegidius/Context-Search/issues/11
