### ISSUE TITLE
Customizations won't save

### ISSUE THREAD

**Issue by vayulove** [odebroqueville/contextSearch#47]
I love this plugin. It's one of my very favorite plugins.  Sadly on my Firefox on macOS after spending time to set up the search engines I want and what order they should come up in on the context menu,  all the work I do gets reverted.   

Sometimes after setting the preferences I'll close it.  Try my settings, and they'll be working, then go back to settings and they'll be reverted.

How do I keep my custom settings?

I'm on Firefox 73. macOS 10.15.2

Maybe you can give me a work around like tell me what file is the config stored in and I can give it read only permissions

It's so frustrating. For me the plugin is unusable with that long list of search choices. Also I have Amazon set up to search all of Amazon not just books, which I use regularly

**Comment by azuravian** [comment]
Having the same problem here.

Firefox 74.0 on Windows 10 (64-bit).

Search engines I've added are still there, but search engines I've removed keep coming back.

**Comment by odebroqueville** [comment]
I'm not able to reproduce this bug. Would you please detail the steps you take to reproduce this bug.

**Comment by vayulove** [comment]
It can be an intermitent thing. But when it's not working it can persist.  Usually several tries and eventually my modifications will stick.  On my mac mini though, I tried over and over and it always kept re-adding all the items I deleted. 

Go to addons then to context search's preferences.  In the section where you're able to customize which search engines are listed in the context dialog, delete several of them,  add at least one new one, and modify one of them. I think it's important to delete several of them and also to rearrange their order.

Also it may seem like your modifications saved properly, but if you close the preferences browse some web pages then return to the preferences, then you may find your previous modifications didn't save properly.

Sometimes I have to try over and over to get my modifications to save, maybe if you can't reproduce the problem, try the above steps several times.
