### ISSUE TITLE
search engines in main context menu not sub-menu

### ISSUE THREAD

**Issue by AdKiller** [odebroqueville/contextSearch#47]
Would it be possible to have my search engines in the main browser context menu not in a sub-menu?

Thanks

**Comment by Smile4ever** [comment]
Currently, there is a limitation of one context menu item per extension. You might want to use the grid feature which can be enabled in the settings of Context Search.

**Comment by AdKiller** [comment]
it would be fantastic if you could add a keyboard shortcut for opening the Context Menu sub-menu, for example X or C, .... 

Then to search Youtube you would have to do:  right-click, press X, press Y
