### ISSUE TITLE
Unable to add Metal Archives, redirects to Google

### ISSUE THREAD

**Issue by Smile4ever** [odebroqueville/contextSearch#48]
When adding Metal Archives with this URL to the search engines, it does not work: https://www.metal-archives.com/search?q=

Originally reported by e-mail.

**Comment by odebroqueville** [comment]
I think the search string is wrong. I got it working with:
https://www.metal-archives.com/search?searchString=%s&type=band_name
Please test on your end and  close this issue if it works.

**Comment by Smile4ever** [comment]
Was confirmed to work using mail, but %s should have been replaced.

**Comment by odebroqueville** [comment]
Pls try and identify one case where it doesn't work, because it's difficult for me to debug something that's working on my end. Thank you for your understanding!

**Comment by odebroqueville** [comment]
Geoffrey, sorry for insisting but I'd like things to move forward! Pls see if you still get a bug with the last push I made to github. If not, then I'll close this issue.

**Comment by Smile4ever** [comment]
* The redirect to Google is behaviour that metal-archives.com itself exposes (it has nothing to do with Context Search) and is considered normal.
* I wasn't able anymore to reproduce the %s not replacing, let's close this issue.
