### ISSUE TITLE
Images for new entries

### ISSUE THREAD

**Issue by proxymus** [odebroqueville/contextSearch#5]
Is it possible to add images for new entries? If so, how can I do that?

Thank you in advance.

**Comment by odebroqueville** [comment]
Do you mean that you'd like to be able to add custom favicons for your search engines?

**Comment by proxymus** [comment]
Yes that was my question.

**Comment by odebroqueville** [comment]
It's currently not possible and it's not on the priority list right now, but the feature may be added some time in the future. Sorry!

**Comment by proxymus** [comment]
It isn't a problem as long there is an auto detection.
