### ISSUE TITLE
Support & and # inside a selection 

### ISSUE THREAD

**Issue by Smile4ever** [odebroqueville/contextSearch#5]
From https://addons.mozilla.org/addon/contextual-search/reviews/913035/

Works well but doesn't seem to recognize characters such as # and &. If included in selected text, everything after it is ignored. Searching for them alone redirects to main search homepage.

**Comment by odebroqueville** [comment]
Yes, I saw that feedback. Definitely should be considered a bug. Off the bat, I’m not sure how to fix this… possibly has to do with URI encoding?

**Comment by Smile4ever** [comment]
> Do you think the following would do the trick?

Yes. See my pull request :)

**Comment by Smile4ever** [comment]
This has been fixed using pull request #6.
