### ISSUE TITLE
Multiple argument search

### ISSUE THREAD

**Issue by beaverrrr** [odebroqueville/contextSearch#50]
Hello!
Recent Firefox update has all but ruined my usual workflow, that heavily relied on context menu search; 
I've used search engine creator and context search x in previous version, they had less than friendly UX, but worked. Your add-on has great UX, but lacks two very important features, for me at least:
First, there is no way to specify where in the search engine URL an argument is, it's always in the end, and from this comes the second: I can't use multiple instances of an argument in a complex search queue, like this:
https://something.something/db/id?a=q&qid=10000&nv=1&v0=QUEUE&v1=QUEUE&v2=QUEUE.
Could you please consider adding this feature? Thanks.

**Comment by odebroqueville** [comment]
@beaverrrr Try using either %s or {search terms} where you'd like the selected text to appear in your search query string, i.e. replace QUEUE with %s. Let me know how it goes.

**Comment by beaverrrr** [comment]
I tried both 
&v0=%s&v1=%s&v2=%s
&v0={search terms}&v1={search terms}&v2={search terms} for search engine URLs
both return v0=QUEUE&v1={search terms}&v2={search terms}/v0=QUEUE&v1=%s&v2=%s. in address bar, and only the first argument is fed to the search engine.

**Comment by beaverrrr** [comment]
Also it seems to me that Grid and Menu items behave differently, for menu items return
&v0=QUEUE&v1=%s&v2=%s and grid items return v0=%s&v1=%s&v2=%sQUEUE

**Comment by odebroqueville** [comment]
Thanks for trying that out and congratulations for picking up this bug! I'll fix this asap and keep you posted.

**Comment by odebroqueville** [comment]
Hi @beaverrrr , I've fixed the bug... the code is now available on Github, but I'm afraid you'll have to wait until the end of next week for the official update via AMO. Cheers
