### ISSUE TITLE
Keyboard shortcut for opening the Context Menu

### ISSUE THREAD

**Issue by AdKiller** [odebroqueville/contextSearch#52]
it would be fantastic if you could add a user configurable keyboard shortcut for opening the Context Menu sub-menu, for example X or C, ....

Then to search Youtube you would have to do: right-click, press X, press Y

Thanks

**Comment by Smile4ever** [comment]
Thank you for your idea. If this can be done in some way and it's not too hard, we will do it in the future. For now, this has a low priority due to other open bugs.

**Comment by AdKiller** [comment]
Is there any chance that it will be implemented in the near future (before Firefox ESR 60.2 - August 2018)?

**Comment by Smile4ever** [comment]
Due do technical limitations, we won't be implementing this anytime soon (no possiblity to close the menus programmatically etc). However, you can open Context Search using only your keyboard:
* Press Alt+D or Ctrl+L to focus the location bar
* Type "cs [keyword] [words to search for]"
    - so for example, "cs wiki Elephant"
* Press Enter / Return

You can set the keywords in the preferences of Context Search.

**Comment by AdKiller** [comment]
That's not the same thing. but thanks anyway. guess I will have to look elsewhere when Firefox breaks all my addons with the release of ESR 60.

**Comment by Smile4ever** [comment]
Thanks for mentioning the other addon, we will take a look to see what we can do.
