### ISSUE TITLE
How to setup reddit.com search

### ISSUE THREAD

**Issue by davidmbesonen** [odebroqueville/contextSearch#53]
Does anyone know how to configure the reddit.com search engine?

**Comment by odebroqueville** [comment]
hi David, simply use https://www.reddit.com/search?q=%s

**Comment by cjscheller** [comment]
Also note that you can limit your search to a specific sub-Reddit using the following:

https://www.reddit.com/r/{{ SUBREDDIT }}/search?restrict_sr=1&q=%s
