### ISSUE TITLE
[request] Search about:config

### ISSUE THREAD

**Issue by GreenWoodie** [odebroqueville/contextSearch#53]
Have been using your extension to great effect, thanks for that. 

I recently discovered that the string: **_about:config?filter=some.configuration.flag_** will display whatever flag I'm looking for in about:confg for Firefox.

Unfortunately your extension won't execute the string (possibly because there is no http prefix?) It would be so very convenient to select some text with name of an interesting switch and go directly to about:config. Would that be a possible using your extension?

**Comment by odebroqueville** [comment]
I don't know if it's feasible, but if it is I'll try and get it to work in Context Search. It's a very legitimate request. Out of interest, may I just ask you where you'd typically be selecting the text corresponding to a specific flag?

**Comment by GreenWoodie** [comment]
Thanks for the response. Thanks too for your consideration of my request.

I guess the usual place to find a reference to a config flag would be within a message or comment on a technical forum. I've been hanging out at the reddit.com/r/Firefox recently, that's where I discovered that this little trick.

**Comment by Smile4ever** [comment]
It's not possible, since you cannot open about urls using WebExtensions.
