### ISSUE TITLE
The location of Config file?

### ISSUE THREAD

**Issue by nemonein** [odebroqueville/contextSearch#54]
Hello.
Thank you for the contextSearch for Firefox. It's really helpful for me.

I want to share the setting with another Firefoxes.
Can you tell me where the config file is?
I'm using Ubuntu 17.10.

Thanks in advance.

**Comment by odebroqueville** [comment]
@nemonein I haven't tried using multiple versions of firefox, but the way I guess it should work is that you use the same login across the different ffx browsers and the extensions and their associated settings should get synced. Once the extension has been installed, the critical file is storage-sync.sqlite which can be found in your Profiles folder for ffx. Hope this helps!

**Comment by nemonein** [comment]
Thanks!
Turning on 'Sync' is the solution.
