### ISSUE TITLE
How do I use 'keyword'?

### ISSUE THREAD

**Issue by nemonein** [odebroqueville/contextSearch#55]
In Preferences I could find these fields.

"Search engine name", "Keyword", "Search engine URL"

What is Keyword for, and how can I use it?
I set a keyword and tried, but there's no action at all.

**Comment by Smile4ever** [comment]
In the omnibox, you can type "cs keyword search terms", for example "cs google appetite". It will search for appetite on Google, using the search engines with their keywords which are defined in the options of Context Search.

**Comment by nemonein** [comment]
Thanks. Now I know how it works.
However, there's something strange here.

I added this site. (Korean movie information site)
```
Name : Naver Movie
URL : http://movie.naver.com/movie/search/result.nhn?query=%s&section=all&ie=utf8
keyword : mvn
```

If I grab text and select Naver Movie, it works fine.
But if I type something like this, it does not work as inteded.

```
cs mvn 올드보이 (in the omnibox)
```

The results is..
```
http://movie.naver.com/movie/search/result.nhn?query=%s&section=all&ie=utf8%EC%98%AC%EB%93%9C%EB%B3%B4%EC%9D%B4
```
It should be
```
http://movie.naver.com/movie/search/result.nhn?query=%EC%98%AC%EB%93%9C%EB%B3%B4%EC%9D%B4&section=all&ie=utf8
```

It does not substitute %s, but adds "%EC%98%AC%EB%93%9C%EB%B3%B4%EC%9D%B4" (It is percent encoding for '올드보이') at the end.

And one more thing.
If I use Context menu as a "Context Menu", I mean, "Select text and right click, then choose Context menu", the result prefers opening in the new tab.
However, if I type 'cs xxx yyyy' in the address bar(omnibox), I prefer the result opens in the same tab. (Right below the address bar.)

Can you make this as an option?

Thank you for reading.

**Comment by odebroqueville** [comment]
Looks like you've spotted a bug! I'm very busy right now, but I'll have a look at it over the weekend. Thanks for your feedback.

**Comment by Smile4ever** [comment]
This bug has been fixed in git.
