### ISSUE TITLE
How to add search, copy/pasted Google Images address, says "error 404" when using

### ISSUE THREAD

**Issue by ttggzz** [odebroqueville/contextSearch#56]
Hi, very glad to find this after Firefox 57, nice work! Suggest adding Google images to list, in the meantime I tried to do it manually. As title says when I use it it does not work, "error 404". 
here is the link I am using:
https://images.google.com/
thanks for your time and any info

**Comment by Smile4ever** [comment]
For Google Images, you have to use:
https://www.google.be/search?tbm=isch&q=

Thank you for using Context Search.

**Comment by ttggzz** [comment]
Spectacular, thanks! Glad to see Ebay in the list, used to have an add-on just for that, which didn't seem to work correctly. Well done!
