### ISSUE TITLE
Add folders to group search engines

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#59]

**Comment by Vingolf** [comment]
I support the idea of grouping search engines,

To reach this goal I suggest the option of using a seperator among search engines in the context menu

The user should have the option to define where he would have set the separator.

**Comment by qwythebroken** [comment]
I'd love to see sub folders as well. I'd still use separators, but between both I'm up to 65 items.

**Comment by odebroqueville** [comment]
@qwythebroken I would gladly have implemented this feature a long time ago, but I'm struggling to understand how to implement nested folders using SortableJS. Without some outside help, I'm not sure I can make this happen. Very sorry!
@cjscheller Hi Carl, first of all I'd like to wish you a Merry Christmas! Would you have the time and be interested to come back on board and try developing this feature? It requires understanding how to apply [this case](https://jsbin.com/fekeroguno/edit?html,js,output) to Context Search. I'm namely not sure what index to use for each search engine or (sub-)folder and how it gets modified on a move (drag & drop).

**Comment by odebroqueville** [comment]
Hi @cjscheller , no worries! I hope you'll enjoy your new role. Thank you for the help you brought for this extension. I think that it's come along a nice way, but it's still missing this essential feature. Happy New Year 2024.

**Comment by odebroqueville** [comment]
This feature has just been released in v5.0.0. Please test it out and let me know if you come across any bugs.
