### ISSUE TITLE
ability to use placeholders when building the search queries

### ISSUE THREAD

**Issue by ssbarnea** [odebroqueville/contextSearch#6]
The current simple interface of just appending the text to the url is preventing the use of web search tools that do require more complex queries where the search text cannot just be at the end of of URL.

This can be achieved if we would have placeholder variables like `SEARCH_STRING` and `SEARCH_STRING_URL_ENCODED` that would be replaced instead of appending the query string to the url.

Current behavior of adding the suffic should kept if no placeholder is found in the base URL.

One good example is performing searches using LogStash / ElasticSearch. What user is likely to want is to perform a log stash query like `message:"ERROR configuring memcached"`, assuming that his original selection was **ERROR configuring memcached** string in a web page.

Now the funnty part is how does the final search URL looks for this query: 

    http://logstash.openstack.org/#dashboard/file/logstash.json?query=message%3A%5C%22ERROR%20configuring%20memcached%5C%22

It looks ugly but the point is that our search string appears in the middle of the URL and is url encoded: as `ERROR%20configuring%20memcached` which is not something unexpected.

Once this feature is implemented a user would only have to configure this base URL:

    http://logstash.openstack.org/#dashboard/file/logstash.json?query=message%3A%5C%22SEARCH_STRING_URL_ENCODED%5C%22

Please let me know what you think about this feature request as I wold prefer not spending a good number of hours trying to implement and getting the PR refused.

I know that the alternative would be to build a simple redirector service but this would need to be hosted somewhere so is better to have it fixed here.

**Comment by odebroqueville** [comment]
This has already been implemented. Please read point 5 of the addon description. Use %s.
