### ISSUE TITLE
Allow users to use custom favicons for search engines

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#64]

**Comment by Vingolf** [comment]
Your are doing a great job with this extension. &#128077;

I support this proposal and I have already an issue with a favicon. 

My problem is not visible in the base64 code in the searchEngines.json 
so I describe some steps to reproduce.

**Issue**
Context Search uses none respectively a wrong favicon for www.ebay-kleinanzeigen.de

**To Reproduce**
Steps to reproduce the behavior:
1. Add www.ebay-kleinanzeigen.de as a search engine to Context Search.
2. Context Search shows in the sub-context menu a placeholder favicon like this
https://api.faviconkit.com/www.ebaykleinanzeigen.de/64
3. The correct icon is this one
https://api.faviconkit.com/www.ebay-kleinanzeigen.de/64

**Feature Request**
1. The possibility to change or to edit the favicon url. 
2. This picture  gives an impression of such a feature.
https://abload.de/img/add-on-swift-selectio8pj02.jpg

**Comment by Vingolf** [comment]
Context Search does not get the right favicon for [ebay-kleinanzeigen.de](https://www.ebay-kleinanzeigen.de).

As a workaround you can get add a favicon manually:

1.  Store the icon on your Computer
 e.g. [ebay-kleinanzeigen.de - favicon](https://www.ebay-kleinanzeigen.de/static/img/favicon.png)

2. Encode the image 
 e.g. with [Base64 Encode Online](https://www.base64encode.org)

3.  Visit Context Search Addons options page
  export (and make a backup of) <br>searchEngine.json to your local disk

4.  Copy and Paste the base64 string into searchEngine.json
5.  Reload the modified searchEngine.json
  the correct icon appears in the context menu

**Comment by odebroqueville** [comment]
You can now (starting from version 4.5.0) use custom png images for your favicons.

## How to add a custom favicon for a search engine

From the Options page, click on the favicon right before the search engine's name. A popup window will open displaying the current favicon and the associated base64 string. Either drag & drop a new png image onto the existing one or paste the base64 string of your new image. Then click on the 'Save' button for your changes to take effect. The popup will automatically close after you click on the 'Save' button.
