### ISSUE TITLE
Default search engine (with possibility to click submenu entry "Context Search")

### ISSUE THREAD

**Issue by matidio** [odebroqueville/contextSearch#68]
New feature:

Would it be possible implement the definition of a default search engine. Then clicking the submenu entry "Context Search" in the Firefox context menu with the left mouse button would launch the default engine using the selected term in the current tab? (feature from Context Search X)
Currently we always have to enter the sub menu to choose an engine. Or did I miss something?

**Comment by odebroqueville** [comment]
Nice idea. Unfortunately, to my knowledge, this isn't feasible with firefox's current web extension API.
