### ISSUE TITLE
AMO review from Sean Ryan (20171201)

### ISSUE THREAD

**Issue by Smile4ever** [odebroqueville/contextSearch#69]
From https://addons.mozilla.org/firefox/addon/contextual-search/reviews/993965/

Very useful extension - thanks! A few questions:
1) Is there any chance you could automatically trim leading/trailing spaces from the selected text before passing the search terms in the associated URL? When you double-click text, Firefox always includes the trailing space and when that is passed on to the website, the required page is not loaded e.g https://dictionary.cambridge.org/dictionary/english/%s I've noticed that most websites themselves do the trimming, but the one above doesn't hence I'm asking for a helping hand from your extension!
2) I've noticed that whenever the Context Search sub-menu appears there's a short (tiny) delay after the menu text shows before the icons for each entry shows. Is there an opportunity here for a performance improvement in the extension, or is this actually Firefox behaviour?
3) The help text says "Right-clicking on a text area inside a web page without previously selecting some text will highlight the word under the mouse pointer". However, this doesn't happen: I've tried a number of websites and if you haven't selected text, then "Context Search" is not listed on the context menu when you right-click. I'm not hassled by this because I always double-click words, so just thought I'd let you know.
Thanks again for your hard-work - the extension out-of-the-box is great.

**Comment by Smile4ever** [comment]
1. Sounds like a bug in Context Search to me. It seems you managed to reproduce the bug we couldn't reproduce anymore. We will definitely look at this.
2. If you are talking about the icons still loading, you need to consider we need to download them first and convert them to base64. Since I do not consider the waiting time that high we probably won't change the behaviour, unless @odebroqueville thinks otherwise.
3. Unfortunately this feature was dropped. We will change the description text accordingly.

**Comment by odebroqueville** [comment]
Thanks for your feedback, Sean. 
2. I am fully aware of the delay to load the icons on first use. I'm also eager to make some improvements here. I've contacted Mat (the author of the besticon API we use for retrieving icons) and asked him if he would consider storing/caching favicons to speed things up a little but it's been 6 days and I haven't heard from him, so I guess he's really busy with other stuff right now!
https://github.com/mat/besticon/issues/31
3. Thanks for spotting that. Will update the AMO description now!

**Comment by Smile4ever** [comment]
1. Actually it's not a bug in Context Search. You need to use https://dictionary.cambridge.org/spellcheck/english/?q= instead and then it will work.

**Comment by Smile4ever** [comment]
I have opened a separate issue for the loading speed of the favicons. If you want to leave feedback about your review or the answers we have provided you can still do that here, but I will close the issue already.
