### ISSUE TITLE
How to search for an exact phrase in quotes?

### ISSUE THREAD

**Issue by Jimmy03** [odebroqueville/contextSearch#7]
For example when you want to search for an exact phrase, you sometimes need quotes

I want to do facebook.com/search/latest/?q="blue moon"

facebook defaults to just facebook.com/search/latest/?q=blue moon (no quotes)

When you go to Twitter's advanced search for an exact phrase it puts in quotes

Also is their an easier way to add new entries to the JSON besides using a text editor?  
I keep having to manually align the formatting in Notepad++

**Comment by odebroqueville** [comment]
Hi @Jimmy03 , sorry for the belated response. Release 3.8.9 will include the option to perform exact phrase searches. The latest release is available on GitHub and will shortly be published to AMO. Thanks for your patience! P.S. You should find it more convenient to edit the JSON file with a proper JSON editor. There are quite a few available on the Windows App Store, but not all are free. 
https://www.microsoft.com/en-us/p/jsoneditor/9nwmlcgc25x3?activetab=pivot:overviewtab

**Comment by odebroqueville** [comment]
Release 3.8.9 is now available on AMO. You can set the option to perform an exact string match in the context menu. Enjoy!
