### ISSUE TITLE
Only all adreses for american or english websites?!

### ISSUE THREAD

**Issue by BlackEagleGermany** [odebroqueville/contextSearch#72]
Hello,

all context search adresses are only for english or american websites.

the search site to found for other contires is a mess.

cann you make a list for maybe germany or different language/ contries??

thanks alot.

**Comment by odebroqueville** [comment]
I'm sorry but right now we really don't have the time to create a list of search engines for each and every country or guess which search engines different users would like. Users still have the possibility of adding whichever search engines they want and save their own list as a JSON file fo backup purposes or to share with others. What we will eventually do in the future is create different language versions, or locales, for the extension, but then we'll need help from our users to translate the preferences page and provide a list of search engines adapted to each locale or language. But we're not there yet!
