### ISSUE TITLE
Feature Request - Add an option to move selected search engines to the root context menu

### ISSUE THREAD

**Issue by theodore** [odebroqueville/contextSearch#73]
I came from Context Search X, which is not compatible with version 57.  Context Search X has a feature to move a search engine to the root context menu.  Can we add this feature?

Example:
![example](https://user-images.githubusercontent.com/475734/33522843-39e1e1d6-d7ac-11e7-920c-5f6c5e56977e.png)

**Comment by Smile4ever** [comment]
Thank you for your idea. Unfortunately, this is currently not possible with the WebExtensions API that we use to build Context Search.

**Comment by theodore** [comment]
Thank you for the link.
