### ISSUE TITLE
Icon grid mode not working on AMO website

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#76]
For some reason, I'm unable to display the icon grid on the web page:
https://addons.mozilla.org/en-US/firefox/addon/contextual-search/reviews/

**Comment by Smile4ever** [comment]
Content scripts are not supported on AMO. This is not a bug in Context Search, but a fallback would be nice.

**Comment by odebroqueville** [comment]
@Smile4ever I think the current fallback is that it uses context menu list.

**Comment by Smile4ever** [comment]
That's correct. There is nothing we can do here then.
