### ISSUE TITLE
Order always alphabetical

### ISSUE THREAD

**Issue by GoodGuyNick** [odebroqueville/contextSearch#77]
After latest release order of search engines always alphabetical. Customized order discarded after browser relaunch.

**Comment by odebroqueville** [comment]
Steps to reproduce the issue:
1) Open the Options page
2) Move a search engine, e.g. move YouTube to just after Twitter and before Wikipedia
3) Restart Firefox browser
4) Visit the Options page

YouTube will have moved back to its original position, instead of remaining in its new position.

**Comment by odebroqueville** [comment]
Release 3.9.2 should fix this issue.

**Comment by artemmarkin** [comment]
Hello.
Version 3.9.2 from addon.mozilla.org - the same problem. 3.9.0 is the last good.

**Comment by odebroqueville** [comment]
So sorry! I thought I had fixed it! Would you please share with me the steps to reproduce the bug. That would be most helpful.

**Comment by artemmarkin** [comment]
Maybe the fix was not included in AMO version?

Actually the steps are the same as above:

    Open the Options page
    Move a search engine, e.g. move YouTube to just after Twitter and before Wikipedia
    Restart Firefox browser
    Visit the Options page

YouTube will have moved back to its original position, instead of remaining in its new position.

**Comment by odebroqueville** [comment]
@artemmarkin  Strange! I'm not able to reproduce the bug on my end. Everything working fine in release 3.9.2. Are you sure that you've successfully updated to 3.9.2? Please try re-installing the extension and let us know.

**Comment by odebroqueville** [comment]
We noticed that the search engines weren't retaining their order in the context menu whilst the order was preserved in the Options page. A fix will be made available in release 3.9.3.

**Comment by artemmarkin** [comment]
Exactly, context menu order is broken. Thank you.

**Comment by artemmarkin** [comment]
Tested 3.9.3, another bug appeared: after browser restart when I try to search via the context menu actually the next search engine is used. For example, I have
1. Google
2. Yahoo
When click Google, the Yahoo search is done. When I click on the last engine in the list then nothing is done.

If you modify order then proper search engines are used until Firefox restart.

**Comment by odebroqueville** [comment]
@artemmarkin Hi, sorry about that and thanks for reporting the issue! I know what the issue is.. will fix it right away.
