### ISSUE TITLE
Search with the wrong search engine is triggered from context menu

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#79]
Tested 3.9.3, another bug appeared: after browser restart when I try to search via the context menu actually the next search engine is used. For example, I have
1. Google
2. Yahoo

When click Google, the Yahoo search is done. When I click on the last engine in the list then nothing is done.

If I modify the order then proper search engines are used until Firefox restart.

_Originally posted by @artemmarkin in https://github.com/odebroqueville/contextSearch/issues/77#issuecomment-638679398_

**Comment by artemmarkin** [comment]
3.9.4 is OK, thank you!

**Comment by odebroqueville** [comment]
@artemmarkin Thank you for your help and patience!
