### ISSUE TITLE
Open search in background tab

### ISSUE THREAD

**Issue by majutsushi** [odebroqueville/contextSearch#8]
At the moment the extension opens the selected search in a new foreground tab. It would be great if there was an option to always open it in a background tab instead, so I can continue reading the page I was on before. Having to switch back and forth between tabs is rather distracting, especially when you want to do more than one search.

**Comment by Smile4ever** [comment]
Hi. We've implemented this for version 3.15. It will soon be available on addons.mozilla.org.

**Comment by odebroqueville** [comment]
Version 3.15 has just been submitted. It should be available by tomorrow. Please let us know if you encounter any issues.

**Comment by majutsushi** [comment]
It's working great, thanks!
