### ISSUE TITLE
Could the right-click menu parent be the default search instead of "Context Search"

### ISSUE THREAD

**Issue by githwithit** [odebroqueville/contextSearch#80]
When I right click highlighted text, the pop-up has option including "Context Search" which cascades to show all my search engines.

Could the "Context Search" option that appears on the initial pop up be the default search option defined within the Context search add on?

This is very handy in the old context search plug I used pre-FF57.

Thanks for your add on!

**Comment by odebroqueville** [comment]
To my knowledge, you can only associate urls to sub-menu items.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/user_interface/Context_menu_items
