### ISSUE TITLE
Periodically Reloads Default Search Engines

### ISSUE THREAD

**Issue by NoEscape** [odebroqueville/contextSearch#82]
contextSearch periodically reloads the list default search engines. When starting Firefox 57.0.4 32bit a notification will popup with the information that the default search engines were loaded. Then the unused search engines have to be unchecked from the context menu or preferences imported.

This behavior has been occurring with earlier releases of Firefox 57.

**Comment by odebroqueville** [comment]
I've been unable to reproduce this bug. Is it still occurring?
To be honest, I'm not quite sure what you mean by "unused search engines have to be unchecked from the context menu or preferences imported"!
