### ISSUE TITLE
No longer works in Firefox 80.0

### ISSUE THREAD

**Issue by pvones** [odebroqueville/contextSearch#84]
It won't show up in the right-click context menu. (Windows 10 64-bit)

**Comment by odebroqueville** [comment]
@pvones would you please provide us with more details: what exactly isn't working? what won't show up in the context menu? If you have a backup of your search engines list, have you tried removing and re-installing the extension, followwed by an import of your search engines?

**Comment by pvones** [comment]
I see, the update process is a bit messy. I had to remove it and add again to get it work. The "Context Search" didn't show up in the right-click popup menu when a text was selected.
