### ISSUE TITLE
sendRemoveListener on closed conduit olivier.debroqueville ...

### ISSUE THREAD

**Issue by pvones** [odebroqueville/contextSearch#87]
Sometimes an url in address bar (typically twitter.com) won't open. When it happens, there are following error messages in Browser Console
![image](https://user-images.githubusercontent.com/2962335/91608997-dceaa780-e976-11ea-913a-e4d7947905fe.png)

**Comment by odebroqueville** [comment]
You shouldn't worry about those messages! At least that's what I was told by Mozilla support!
