### ISSUE TITLE
Feature request: display (some) entries directly in the context menu

### ISSUE THREAD

**Issue by Hypernut** [odebroqueville/contextSearch#88]
Hi, i use this excellent add-on a lot. Therefore I have to click the context menu -> sub menu -> search engine entry   a lot. 
So it would be great if you could add a the option for each search engine entry, if it should be displayed in the sub-menu (as it is now) or **directly** in the context menu.
Thanks!!

**Comment by odebroqueville** [comment]
Unfortunately, Mozilla's current web extension API doesn't allow placing menu items (e.g. search engines) in the top level. Only sub-menu items are possible. You should place your feature request by Mozilla.
