### ISSUE TITLE
Preferences aren't persistent

### ISSUE THREAD

**Issue by pvones** [odebroqueville/contextSearch#88]
When I set any preferences, _[X] Make the new tab or window active for instance_ and close Firefox, it won't be checked next time the Firefox is started.

**Comment by odebroqueville** [comment]
Would you please provide us with the versions you are using of the extension, browser and your OS.

**Comment by pvones** [comment]
4.0.0 (Firefox 80.0, Windows 10 x64).

**Comment by odebroqueville** [comment]
I wasn't able to reproduce this issue on macOS Catalina using ffx 80 and CS 4.0.0.

**Comment by pvones** [comment]
Where is it stored?

**Comment by odebroqueville** [comment]
In storage-sync-v2.sqlite under the variable tabActive as shown below:
`{"options":{"disableAltClick":false,"displayExifSummary":true,"displayFavicons":true,"exactMatch":false,"forceFaviconsReload":false,"forceSearchEnginesReload":false,"lastTab":false,"optionsMenuLocation":"bottom","resetPreferences":false,"tabActive":true,"tabMode":"openNewTab"}}`

**Comment by pvones** [comment]
I don't have such file in the Thunderbird profile. **storage.sqlite** only.

**Comment by odebroqueville** [comment]
It's not a Thunderbird profile, it's Firefox! Go to Help > Troubleshooting Information and click on the button to show your profile folder.

**Comment by pvones** [comment]
Sorry :-)
