### ISSUE TITLE
Last version of plugin (4.0.0) did not work without plugin reinstalling

### ISSUE THREAD

**Issue by manfromix** [odebroqueville/contextSearch#89]
1. It was absent in context menu
2. list of search engines in settings was empty
and stayed empty after settings reset
3. Tries to add custom engine were not successful

Without special steps for its reproducing.

It can be repaired by plugin reinstalling.

Firefox 80.0 64-bit
Content Search 4.0.0
Windows 10 corporate ltsb 64-bit

**Comment by Jimmy03** [comment]
I just installed this version and it seems to work ok, I had to restart Firefox but I didn't need to reinstall the plugin.

Also, how can I remove the ContextSearch Icon from Firefox's Urlbar?
I just want to keep the Urlbar clean visually

**Comment by odebroqueville** [comment]
The firefox update to version 79 broke Context Search by clearing user's search engines from storage sync (where they were previously stored). Version 4.0.0 now stores search engines in local storage to avoid the quota limitations imposed on storage sync as of ffx 79. Many users have recently seen Context Search updated from version 3.72 to version 4.0.0 in parallel to ffx updating to version 79 and then 80. 
https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/
We have filed a bug with Bugzilla to fix the issue but for those who've already updated to ffx 79, the only solution we have is to re-install Context Search and import your custom list of search engines (hoping everyone has a backup!).
https://bugzilla.mozilla.org/show_bug.cgi?id=1661325

@Jimmy03 sorry, but I don't think you can get rid of the icon... it's linked to a page action that was requested by a number of users. We just can't make every single feature optional, so please try ignoring the icon if it's of no use to you.

**Comment by Jimmy03** [comment]
Should everyone reinstall the addon? Or only if it doesn't show in the context menu?

**Comment by odebroqueville** [comment]
@Jimmy03 If the addon is behaving as expected then I don't think you need to re-install. I'd recommend re-installing the addon for users who lost their custom list of search engines and saw it replaced by the default list of search engines. Anyone whose backed up his or her search engines and wants peace of mind will be better off removing the extension, re-starting the browser and re-installing the extension and finally importing their list of search engines.
