### ISSUE TITLE
Neaten settings layout

### ISSUE THREAD

**Issue by bakaoniisan** [odebroqueville/contextSearch#89]
At the moment the settings page lists for searches is arranged like so;

DuckDuckGo
Remove
Google
Remove
Bing
Remove
...

It makes it difficult to scan text quickly

Much easier to read would be; 

DuckDuckGo
Google
Bing
...

Could you maybe move the "remove" button to end of line so the search engine list is easier to read.

**Comment by odebroqueville** [comment]
Would you please let us know on which device you're experiencing this issue. On a desktop computer, the Remove buttons are displayed at the end of each line.

**Comment by bakaoniisan** [comment]
58.0.2 (64-bit)
Ubuntu 16.04.3  (Linux) Desktop
1080p display

I'll try uploading an image.
https://s9.postimg.org/j0ri1egi7/Screenshot_from_2018-02-14_21-52-39.png

There is a very small chance is has to do with my font settings but I don't think so. I tested them and no other addon has formatting issues. I also reduced front size and it changed nothing. Still, I may have missed something.

**Comment by bakaoniisan** [comment]
I created a new profile. Same result in image I uploaded.

**Comment by odebroqueville** [comment]
To give you an idea, this is what it looks like on macOS...
![screen shot 2018-02-14 at 16 46 42](https://user-images.githubusercontent.com/4818315/36213479-217d9704-11a7-11e8-92f1-9c3961fab6cd.jpg)

so I'm a bit puzzled!

**Comment by odebroqueville** [comment]
Are you using the latest version 3.58 of Context Search ? I also noticed something else that doesn't seem right on your screenshot: the keywords are all set to "undefined"!

**Comment by odebroqueville** [comment]
I've made a minor tweak in version 3.59 which I have pushed here into Github. Would you be able to test it and tell me if it fixes your issue?

**Comment by bakaoniisan** [comment]
I'm using 3.58. I also installed 3.58 in a new profile. Same result.

I have no Idea of how to install 3.59 from Github. How do I do that?

**Comment by Smile4ever** [comment]
@bakaoniisan You can download a ZIP file: https://github.com/odebroqueville/contextSearch/archive/master.zip
Then you extract that ZIP file, and you go to the URL about:debugging. There you point to the manifest.json file (which is in the ZIP file). That way you will be working with the newer contextSearch version (until you restart Firefox).

**Comment by bakaoniisan** [comment]
@Smile4ever Thanks

@odebroqueville All fixed. Thank you.

![screenshot from 2018-02-15 05-25-13](https://user-images.githubusercontent.com/29756353/36221054-c75dc1be-11b4-11e8-9b87-784e53cbed0b.png)

**Comment by odebroqueville** [comment]
You're most welcome. May I just ask you if you set the keywords to "undefined" or if they were set that way from the start. That could be a bug we would have to look into.

**Comment by bakaoniisan** [comment]
Older version set them as  "undefined" by default.
 At some point the newer version fixed that and it is now "Keyword" when left blank.

I never updated the keywords for searches because they don't work. I thought that was just because FF had not added API, like the same issue with "Integration with Firefox search engines".

**Comment by odebroqueville** [comment]
Would you please try something for me: for the search engine DuckDuckGo, replace undefined by ddg and then click on the button "Save preferences". Then, in the url address bar, type "cs ddg dogs" and hit enter. Let me know what happens...

**Comment by bakaoniisan** [comment]
"cs ddg dogs"

Yes that works.

I did not read in the addon page that I must use - cs [keyword] [SearchTerms]

Now after searching the GitHub main page, I found it.

You may have less people like me, who don't read everything, missing this information if you added it to the addon page. Maybe higher up on GitHub page too.

**Comment by odebroqueville** [comment]
Thanks for letting me know. I'm glad it's working.
I totally agree with you that the description needs some re-work! I believe most users don't bother reading it. After all, who reads the instruction manual! I think I have to make the description more concise and straight to the point. Maybe simply giving examples would suffice as you say.
