### ISSUE TITLE
Support for POST request

### ISSUE THREAD

**Issue by koug44** [odebroqueville/contextSearch#9]
Hey,

Would it be possible to add support for POST request ?

In my case, I'm not using the extension for public search engine but for internal work-related ones.
And most of them support only POST request.

Thanks for your work

**Comment by odebroqueville** [comment]
I'm sorry but your request is too specific, so it won't be addressed. Regards.

**Comment by odebroqueville** [comment]
Hi @cjscheller , do you understand this request?

**Comment by odebroqueville** [comment]
@koug44 This is now supported by version 4.7.1. Sorry for the long delay! Double-click in an empty search box, then at least enter a search engine name. The search engine should be added on the extension's options page.
