### ISSUE TITLE
Custom search URL for duckduckgo cannot be used

### ISSUE THREAD

**Issue by 2SI3NX** [odebroqueville/contextSearch#90]
Say for instance a user custom makes his duckduckgo URL, eg. the user's custom URL is:
https://duckduckgo.com/?kae=g&kd=-1&kg=p&kh=-1&kf=-1&k18=-1&kaf=-1&kai=1

How would you fix this to make it work within the context search?

**Comment by odebroqueville** [comment]
Some of the parameters (there is no g theme for kae; there are no k18 or kai parameters) you chose don't exist! Check your parameters using this reference page: https://duckduckgo.com/params
I tried https://duckduckgo.com/?q=%s&kae=d&kd=1&kg=p&kh=1&kf=-1&kaf=-1
and it worked fine. You need to insert q=%s& right after the ? and before kae.

**Comment by 2SI3NX** [comment]
thanks. works!
