### ISSUE TITLE
The position of options in the context menu isn't changed and saved when it is modified in the extension's preferences page

### ISSUE THREAD

**Issue by Lynx560** [odebroqueville/contextSearch#91]
I would like to have the ability to multi-search using the options menu instead of using the omni-bar command. At one time, the menu appeared under the list of search engines, but it has disappeared.
I went into Options and selected "At the bottom" from the drop-down list
![9-27-2020 10-11-13 PM](https://user-images.githubusercontent.com/72001888/94446696-d7db6c80-015d-11eb-97ad-d3d7e42ea467.jpg)

but after checking, it did not work.
When I returned to the Options page, the option had reverted to the default "Neither (hide the options menu)"
![9-27-2020 10-12-16 PM](https://user-images.githubusercontent.com/72001888/94446713-dca02080-015d-11eb-9d55-a5fe8c0da87b.jpg)

How can I ensure the option(s) I want to use are enabled & working ?

OS: Windows 7

Browser: Firefox 81.0 (64bit)
~Javascript enabled
Addons installed & enabled
~Adblock Plus
~Context Search
~Copy Plain Text
~HTTPS Everywhere
~New Tab Tools
~Tampermonkey
~Video Ads Blocker
~Video DownloadHelper

**Comment by odebroqueville** [comment]
@Lynx560 Please start by backing up your custom search engines by exporting them. Next, please try re-installing Context Search and then importing your search engines. Let us know how it goes.

**Comment by Lynx560** [comment]
Thank you for your reply.

I backed up my custom search engines using the "Import/export search engines" option as asked & saved the JSON file on my HDD. Then I deleted (removed) the addon & re-installed from the Mozilla Addons page:
https://addons.mozilla.org/en-US/firefox/addon/contextual-search/

I then imported my search engines as instructed (which worked perfectly), and re-started Firefox.
Next, I opened the CS options & changed the "Position of options in the context menu" selection from the default "Neither hide the options menu" to "At the bottom"
![9-29-2020 4-09-59 PM](https://user-images.githubusercontent.com/72001888/94626352-cc786600-026f-11eb-8263-edba91a82e97.jpg)
I then waited more than 1 minute to allow it to auto save.

I re-started FF and tested to see if the change worked, It did not...
![9-29-2020 4-24-03 PM](https://user-images.githubusercontent.com/72001888/94626618-51637f80-0270-11eb-9c55-4702f38eaa72.jpg)

I went back to CS Options to check if the selection was as I set it, but it was not.
![9-29-2020 4-11-25 PM](https://user-images.githubusercontent.com/72001888/94626683-6fc97b00-0270-11eb-87b9-69629765d4a1.jpg)

I see that a "Save" button has been suggested by others. Maybe that will stop the addon from reverting to default each time it is opened.

I truly hope this issue can be resolved.


Thank You for your time

**Comment by odebroqueville** [comment]
@Lynx560 You're absolutely right: this is a bug. However, the default setting for the options position in the context menu is "At the bottom". Anyway, I'm investigating and will provide you with a fix asap.

**Comment by Lynx560** [comment]
Thank you

Strange that the default is "At the bottom". It has ALWAYS been "Neither ..." when I install it.

Either way, being able to choose which option would be preferable.

**Comment by odebroqueville** [comment]
@Lynx560 Do you know how to test an extension by cloning from GitHub? The latest release 4.1.0 now available on GitHub should fix things. Needs some testing now to be sure.

**Comment by Lynx560** [comment]
Sorry ... I don't know how to clone.

I will try to update from my browser.

Be back in a minute.

**Comment by odebroqueville** [comment]
@Lynx560  There's a not so complicated way to test things if you want to give it a try:
1) download the Zip file containing all the Context Search code from the green "Code" button here:
https://github.com/odebroqueville/contextSearch
2) extract it to a folder of your chosing
3) type about:debugging in ffx address bar
4) in the left margin click on "This Firefox"
5) click on the box "Load Temporary Add-on" and select the manifest.json file from the folder where you extracted the code
6) Have fun testing!
Please note that when you close the browser, then the extension is unloaded.

**Comment by Lynx560** [comment]
I'll give it a try ....

I hope it doesn't remove the original addon.

I guess I can always re-install if necessary

**Comment by Lynx560** [comment]
AHA !!!

It worked !!!
![10-1-2020 12-36-42 PM](https://user-images.githubusercontent.com/72001888/94855189-f9995580-03e2-11eb-9e73-7734ff584a00.jpg)


Testing to see if the other options work

**Comment by Lynx560** [comment]
At the top works too !!!
![10-1-2020 12-39-16 PM](https://user-images.githubusercontent.com/72001888/94855351-39f8d380-03e3-11eb-912c-f9c657ea02bb.jpg)

**Comment by Lynx560** [comment]
Can the "Search this site with Google" be changed to another search engine .... like Bing ?

**Comment by odebroqueville** [comment]
@Lynx560 Perhaps we'll look into this at some point in the future. The difficulty arises if the search terms for searching a specific site differ. When you search a specific site using Google, you use: "site: www.website_to_search.com". I don't know if it's the same for Bing or DuckDuckGo?
