### ISSUE TITLE
Allow users to search the current website by chosing a search engine from a list not limited to Google

### ISSUE THREAD

**Issue by odebroqueville** [odebroqueville/contextSearch#93]
Currently the context menu displays "Search this site with Google" only. The goal is to offer to option to chose from the following search engines (and not just Google):
- Google
- Bing
- DuckDuckGo
- Ecosia
- Lilo
- Qwant
- Startpage
- Swisscows
- Yahoo

This should be feasible as each of the above search engines supports searching with the parameter "site: ". The default search engine used would be selected from a dropdown list in the extension's preferences page.

**Comment by Lynx560** [comment]
Testing now

**Comment by odebroqueville** [comment]
@Lynx560 I deleted 4.1.0 from AMO b/c there's a huge bug! I don't recommend updating yet. Regarding the above issue, it's actually a feature request hence the label "enhancement". It is something we need to work on; it's a work in progress and hasn't been released yet. When the issue is closed, then it will have been released.

**Comment by Lynx560** [comment]
Thank you for this.... but I am confused what it does. I assumed that it would search whichever Search Engine you chose with the phrase you highlighted
![10-18-2020 7-47-48 PM](https://user-images.githubusercontent.com/72001888/96396142-53d43d80-117b-11eb-8375-4ec492ab5bfc.jpg)
but all it did was search the website I used to get the phrase from.
![10-18-2020 7-48-53 PM](https://user-images.githubusercontent.com/72001888/96396230-95fd7f00-117b-11eb-96d4-aa92685dedee.jpg)

Can it be set to search based on the phrase that is selected .... not only in the site that it came from ?

**Comment by odebroqueville** [comment]
@Lynx560 I'm not sure that I understand what you are trying to do! If you want to search using Bing, then you just select that search engine in your list above (i.e. the second item in your list). "Search this site..." means that you are only searching the current active website.
