### ISSUE TITLE
Context Search no longer appears in the context menu

### ISSUE THREAD

**Issue by RedQuine** [odebroqueville/contextSearch#94]
Since updating to Firefox 81.0.1 (64-bit, Linux) Context Search no longer appears on my context menu. I have checked my preferences for the extension, and everything appears to be exactly the same as it was before the upgrade.

**Comment by odebroqueville** [comment]
@RedQuine Sorry for the trouble. I had released version 4.1.0 a few days ago before realizing there was a major bug! I'm working on a fix. In the mean time, please revert to version 4.0.0 which is available here: https://addons.mozilla.org/en-US/firefox/addon/contextual-search/versions/
