### ISSUE TITLE
"Remove" button in wrong place again

### ISSUE THREAD

**Issue by bakaoniisan** [odebroqueville/contextSearch#97]
Sorry, :)

Version 3.6X brought back the problem that was fixed when you posted 3.59 for me to test.
![screenshot from 2018-02-26 01-40-36](https://user-images.githubusercontent.com/29756353/36642629-423757d2-1a3a-11e8-80dc-46ccd8f3132b.png)

I'm beginning to think this is a Firefox bug (on linux)

**Comment by odebroqueville** [comment]
Sorry about that! I'll look into it  right away. Was version 3.64 ok? Or has the remove button been on the next line since I changed it from text to an icon?

**Comment by odebroqueville** [comment]
Would you please test the changes I've made in the folders branch and let me know if things are fixed? Thanks.
![screen shot 2018-02-25 at 17 16 41](https://user-images.githubusercontent.com/4818315/36643793-ae40acd8-1a50-11e8-8982-393d5870d9aa.jpg)

**Comment by bakaoniisan** [comment]
I tested all the 3.60 - 3.65 series. All have the same issue.

3.59 that I loaded with about:debugging worked fine just like the new version I just tested with about:debugging. All good. (see below)
![screenshot from 2018-02-26 05-54-29](https://user-images.githubusercontent.com/29756353/36645272-f61e076e-1a5d-11e8-88e5-1f5f20622bcb.png)

It really does seem like a bug in firefox (linux version).
I'll bet that if you uploaded the new code I just tested which works, it'll not work when firefox updates the extension.

I feel like spending too much time on this will make things overly difficult.
What can I do to help?
I uploaded the html of good and bad pages (below). Maybe it helps work out something about code, buttons or whatever.
[Context.zip](https://github.com/odebroqueville/contextSearch/files/1756614/Context.zip)

**Comment by bakaoniisan** [comment]
Looking closely at the screenshots I uploaded, doesn't the scaling seem different?

I tested 3.65 on a live 18.3 Mint iso with firefox 57 so everything is super clean. Same problem. 
![screenshot from 2018-02-26 06-40-21](https://user-images.githubusercontent.com/29756353/36645659-1ce4c5b2-1a64-11e8-8fd8-7647df0aa75f.png)

**Comment by bakaoniisan** [comment]
Found it!

Depending on distro, a different default theme may be used. Maybe the controls that are slightly different sizes and firefox ignores that when creating a border, container or whatever the box around everything is called.

If I cycle through the controls in system themess, some will work and some will not.
As to know how this ties into the test versions you posted always work when used in about:debugging but not when installed/updated, I don't know.

**Comment by odebroqueville** [comment]
Good to know the latest test version is working. I haven't released these changes on AMO yet, so I believe it's normal if the latest release on AMO isn't working. I'll let you know when I push the corrections to AMO. It might be a week or two because I'm implementing a new set of features along with these corrections. Please bare with me!

**Comment by Smile4ever** [comment]
I will see whether I can come up with a solution that does not create a gap in the layout on the right.
